### ISSUE TITLE
Search streets based on other connected streets for geoconding in Nominatim

### ISSUE THREAD

**Issue by NasserTahani** [openstreetmap/Nominatim#1224] opened 2018-11-04 07:50 UTC
We installed Nominatim and used it for searching POIs in a local server. I've explored the address format in Nominatim which is in the following order:

- road
- neighborhood
- suburb
- city
- boundary
- county
- province
- country

In this order, I can find sample address like "تهران، حکیمیه، بلوار بهار" and "تهران، حکیمیه، نشوه" but when I want to search street called "نشوه" which is connected to street "بلوار بهار" like this "تهران، حکیمیه، بلوار بهار، نشوه" Nominatim can't find the street and returns no result.

I've used 'addr:street' key for the second street and set the name of the first street as its value. But no success obtained.

```
<way id="4907958" version="1" timestamp="2018-10-09T11:48:38Z" changeset="0">
        <nd ref="5968973949"/>
        <nd ref="5968973950"/>
        <tag k="highway" v="living_street"/>
        <tag k="maxspeed" v="20"/>
        <tag k="name" v="نشوه"/>
        <tag k="addr:street" v="بلوار بهار"/>
</way>
```
Also, I used AssociatedStreet to create a new relation between two streets.

```
<relation id="-659328632">
      <tag k="type" v="associatedStreet" /> 
      <member type="way" ref="4907958" role="street" />
      <member type="way" ref="136605953" role="street" />
</relation>
```
This is the link to gis.stackexchange [question ](https://gis.stackexchange.com/questions/300952/searching-a-street-based-on-a-connected-street-in-nominatim)which you can see the screeshot of the streets on the map.

**Comment by mtmail** [comment] 2018-11-04 10:18
Nominatim can't handle intersection searches. It will only look for one street, adding another will actually make a result less likely to be found. New York's block addresses are a good example.

"6th ave, 23rd str, new york, usa" yields no results, while "6th ave, new york, usa" and "23rd str, new york, usa" individually do. 

For "6th ave" https://nominatim.openstreetmap.org/search.php?q=6th+ave%2C+new+york%2C+usa you'll see Nominatim only returns a single street section (a way in OpenStreetMap), not the full street. It doesn't look at `associatedStreet` (and would be too much to create a relation for every intersection).

Looking up each connected street can get (data query time) expensive unless those are pre-computed. 

Closing as duplicate of https://github.com/openstreetmap/Nominatim/issues/123

**Closed by mtmail** 2018-11-04 10:18 UTC
