### ISSUE TITLE
When I import data for the second time:ERROR: database already exists (pgsql:dbname=nominatim)

### ISSUE THREAD

**Issue by dengyichao** [openstreetmap/Nominatim#1560] opened 2019-11-08 05:50 UTC
Hello, when I import data for the second time, he will report that the database already exists. If I delete the previous database data, then the previous data is not wasted? If I import. / utils / setup.php -- osm-file.. / naming-3.4.0/data/china-latest.osm.pbf -- all 2 > & 1 "tee setup.log for the first time and open localhost / naming access successfully, I will use. / util / setup.php -- osm- file. / naming-3.4.0 / data / new-york-latest.osm- asm.pbf -- all 2 > & 1" tee setup.log to import new data: he will report when importing new data: he will report that he will import new data.Wrong:

2019-11-08 13:43:54 == module path: /srv/nominatim/build/module

2019-11-08 13:43:54 == Create DB

ERROR: database already exists (pgsql:dbname=nominatim)

string(48) "database already exists (pgsql:dbname=nominatim)"

So what should I do when I need to import new data?

**Comment by itz-sudo** [comment] 2019-11-08 10:02
It means database already exists. You should drop the db if already exists and if you want new. You should run `dropdb nominatim` to drop nominatim db

**Comment by nslxndr** [comment] 2019-11-08 10:03
Duplicate of #224 (see [issue comment](https://github.com/openstreetmap/Nominatim/issues/224#issuecomment-70646612)).

**Closed** 2019-11-08 12:50 UTC
