### ISSUE TITLE
Data missing from diff imports

### ISSUE THREAD

**Issue by mgaidia** [openstreetmap/Nominatim#1590] opened 2019-12-01 10:54 UTC
Object: https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=660816431&class=highway

Issues:
- Postcode should be: CB24 1DA
- The house numbers (1-6) are mapped correctly in Openstreet map but do not appear in the address Database.

**Comment by lonvia** [comment] 2019-12-01 14:02
The missing postcodes are just a consequence of the missing buildings, so not that interesting (adapted the issue title to reflect that).

I've tried to trace down the missing buildings. They should have come in with diff [3625374](https://planet.osm.org/replication/minute/003/625/374.osc.gz). According to the log entries in the database this diff was correctly downloaded and applied. I've tried downloading the diff again with pyosmium-get-changes and the resulting .osc correctly contains the building.

So either osm2pgsql was interrupted in a bad way while reading the change or there is an issue with applying the changes. I don't have the logs anymore for August 2019 where I could check if something went wrong with the import. I'd need a more recent example for that.

**Comment by lonvia** [comment] 2019-12-01 16:56
There is actually an easily repeatable bug in the osm2pgsql import. Just repeatedly update the way in question and it will alternately appear and disappear.

The issue is that `has_class()` and `copy_out_main_tag()` have a slightly different logic how to handle tags that require a name to be present. In fact, it is a bad idea to have this logic in two different places. Instead we should just post-process the list of main tags in `process_tags()`.

Fix has to wait until after https://github.com/openstreetmap/osm2pgsql/pull/1008 has been merged.

**Comment by lonvia** [comment] 2019-12-01 17:05
@mgaidia I've resurrected the houses in that street. Better not touch them until this bug is actually fixed. ;)

For the rest of the database there might actually be a reimport necessary as basically every house with house number that has been edited an odd number of times is effected. We'll see.

**Comment by mgaidia** [comment] 2019-12-02 07:58
Thanks @lonvia, Fantastic work!
Can you please make sure house number 5 is included as well.

**Comment by lonvia** [comment] 2019-12-02 08:49
Done. Any further data will have to wait until after the fix though.

**Comment by lonvia** [comment] 2019-12-16 20:55
Fixed with bc68ff1e43f2527039640b8642bbe533814a3561.

I'll probably do a reimport over Christmas when things are a bit more quiet on the server.

**Closed by lonvia** 2019-12-16 20:55 UTC
