### ISSUE TITLE
failure to resolve "One Market Place"

### ISSUE THREAD

**Issue by RichMorin** [openstreetmap/Nominatim#856] opened 2017-11-21 00:23 UTC
The "Manchester Grand Hyatt San Diego" is located at "1 Market Place".  However, some web pages (eg, https://www.hyatt.com/content/dlp/en/sandiego/hotels.html) list it as being at "One Market Place", which Nominatim fails to resolve. I believe this to be an instance of a more general problem in handling spelled-out numbers in addresses.

-r

**Comment by lonvia** [comment] 2017-12-14 23:19
Duplicate of #173.

**Closed by lonvia** 2017-12-14 23:19 UTC
