### ISSUE TITLE
Address/ building # data showing with commas, instead of end-user friendly format

### ISSUE THREAD

**Issue by omgitsgela** [openstreetmap/Nominatim#918] opened 2018-02-14 10:44 UTC
When searching for a POI on Nomatim (or, by extension, on OSM itself,) addresses are being returned with the building number followed by a comma, which is not user friendly or stylized within the commonly accepted format for my locale in the USA.

![nomatim address](https://user-images.githubusercontent.com/25420944/36200161-c7c319d0-1149-11e8-8855-2956c6e953d8.png)

The styling currently shows:

Little Caesars, 160, Winthrop Avenue, Lawrence, Essex, Massachusetts, 01843, United States of America

The better, user friendly format would be:
Little Caesars, 160 Winthrop Avenue, Lawrence, Massachusetts, 01843
(Address is concatenated with street without comma, county information is optional, but could be included, and country is unnecessary for most people)

**Comment by lonvia** [comment] 2018-05-05 21:41
This is tricky to do because it depends on the preferences of the Nominatim user (the placement of the housenumber) _and_ the country the result is in (whether or not county is shown). We do plan to have localized address at some point (see #213) but if there ever will be user specific formatting is doubtful.

Closing as duplicate of #213.

**Closed by lonvia** 2018-05-05 21:41 UTC
