### ISSUE TITLE
No results found whereas exact same address in nominatim

### ISSUE THREAD

**Issue by mguldner** [openstreetmap/Nominatim#1679] opened 2020-02-13 09:44 UTC
If I search 

"26, Rue des Potiers d'Étain, Actipôle, Grange-aux-Bois, Metz, Moselle, Grand Est, France métropolitaine, 57070, France", I find this :
![image](https://user-images.githubusercontent.com/11960112/74421554-84761180-4e4d-11ea-86e7-ddc811691fe8.png)

But if I search with the exact same address as the found by Nominatim : 

"**Brico Dépôt,** 26, Rue des Potiers d'Étain, Actipôle, Grange-aux-Bois, Metz, Moselle, Grand Est, France métropolitaine, 57070, France"

![image](https://user-images.githubusercontent.com/11960112/74421643-a7082a80-4e4d-11ea-8fc7-d9baa8845bb1.png)

**Comment by lonvia** [comment] 2020-02-21 15:17
This a a duplicate of #164.

As a general rule: there is no guarantee that searching by the displayed name gives exactly the same result.

**Closed by lonvia** 2020-02-21 15:17 UTC
