### ISSUE TITLE
Reverse Geocoding - zip breaks the result

### ISSUE THREAD

**Issue by boldtrn** [openstreetmap/Nominatim#691] opened 2017-03-27 06:06 UTC
I am having some troubles with reverse geocoding of: `Col du Galibier, 73450, Valloire, France`. Keeping the zip, no results are found, removing the zip, the correct results are found (`Col du Galibier, Valloire, France`). 

But the postocde is part of the [display_name and the result](https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=Col%20du%20Galibier%20Valloire%2C%20France). Any idea why this happens?

**Comment by mtmail** [comment] 2017-03-27 09:34
I'll mark this as duplicate of https://github.com/openstreetmap/Nominatim/issues/403 but of course thank you for that test case!

We have a problem description plan to fix that at https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2017/Project_Ideas/Nominatim_postcode_project

P.S. kurviger is great

**Closed by mtmail** 2017-03-27 09:34 UTC

**Comment by boldtrn** [comment] 2017-03-28 00:49
> I'll mark this as duplicate of #403 but of course thank you for that test case!

Thanks, I haven't seen #403. Sorry for opening a duplicate :)

Here are a couple more examples (not sure if it's related to `Col` but I received these examples from a user recently):
- [Col de Montgenèvre, 05100, France](
https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=Col%20du%20Mont%20Cenis%2C%2073480%2C%20Val-Cenis%2C%20France&limit=10&bounded=1&viewbox=-180,82.5127018432178,180,-81.59805383379877)
- [Col de l'Iseran, 73480, Bonneval-sur-Arc, France](https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=Col%20de%20l%27Iseran%2C%2073480%2C%20Bonneval-sur-Arc%2C%20France&limit=10&bounded=1&viewbox=-180,82.5127018432178,180,-81.59805383379877)
- [Col du Chaussy, 73300, Pontamafrey-Montpascal, France](https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=Col%20du%20Chaussy%2C%2073300%2C%20Pontamafrey-Montpascal%2C%20France&limit=10&bounded=1&viewbox=-180,82.5127018432178,180,-81.59805383379877)
- [Col de Montgenèvre, 05100, France](https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=Col%20de%20Montgen%C3%A8vre%2C%2005100%2C%20France&limit=10&bounded=1&viewbox=-180,82.5127018432178,180,-81.59805383379877)

> P.S. kurviger is great

Thanks, glad you like it. Nominatim is an awesome project as well!
