### ISSUE TITLE
Problems with query returns

### ISSUE THREAD

**Issue by cheeta2018** [openstreetmap/Nominatim#987] opened 2018-03-23 01:41 UTC
I have two problems about the query returns，for example:  https://nominatim.openstreetmap.org/search.php?format=json&q=chengdu[university]&polygon_geojson=1&addressdetails=1&limit=1000.
The results of this query is only 11, Actually more than 11 universities in chengdu, and the limit I set is 1000. 
If I use : 
 https://nominatim.openstreetmap.org/search.php?format=json&q=china[university]&polygon_geojson=1&addressdetails=1&limit=1000, 
The results of this query is  50 at most. So why?

Another question: 
https://nominatim.openstreetmap.org/search.php?format=json&q=china[cafe]&polygon_geojson=1&addressdetails=1&limit=1000.
The results of this is also 50 at most，and not all is the "cafe",but some are the "pub".Why this ?

I hope that someone can answer me  in detail about the two question.
Thank you very much!!!

**Comment by lonvia** [comment] 2018-03-23 08:20
Exact duplicate of #984.

**Closed by lonvia** 2018-03-23 08:20 UTC
