### ISSUE TITLE
Nominatim ranks keyword results higher than exact results

### ISSUE THREAD

**Issue by LoremoCH** [openstreetmap/Nominatim#1092] opened 2018-07-14 15:54 UTC
It looks like nominatim has some keywords like house, shelter, station and translations of thoes. It uses them to get better results.

For example if you Enter "Bahnhof Zürich Tiefenbrunnen" (Bahnhof is German for train station) the first result is [node 1291611923](https://www.openstreetmap.org/node/1291611923) which has the tags for a train station. 

Unfortunately it ignores results which match more, but are missing tags which are linked with the keywords. Two examples:

### E-Shelter data center at Rümlang (CH)
- [Way 370529088](https://www.openstreetmap.org/way/370529088)
- Keyword: shelter
- Query: "E-Shelter, Rümlang"
- Result: Different objects which are tagged as shelter (most are bus stops) in the area. The data center is not in the results.

### Yarra House at Fairfield in Melbourne (AU)
- [Way 401280243](https://www.openstreetmap.org/way/401280243)
- Keyword: house
- Query1: "Yarra House, Melbourne"
- Query2: "Yarra House, Fairfield"
- Result1: Many parks, stations, houses and other things in Melbourne. _Probably because much is named after the river Yarra._
- Result2: Only the suburb relation for Fairfield.

**Comment by mtmail** [comment] 2018-07-17 16:16
https://github.com/openstreetmap/Nominatim/issues/1084 seems to be another example where "Fontana" (city) gets interpreted as keyword "fountain" first and lots of fountains are returned.

**Comment by lonvia** [comment] 2018-07-17 20:32
The results have relatively little to do with special keywords. The search terms are partial matches for the names of the objects you are looking for. Nominatim isn't particular good at those because it doesn't know what "good" abbreviations of the name in question are.

Duplicate of #94.

**Closed by lonvia** 2018-07-17 20:32 UTC
