### ISSUE TITLE
Search result for 'United States of America' is incorrectly placed in Alaska

### ISSUE THREAD

**Issue by Rohan-Bapat** [openstreetmap/Nominatim#1291] opened 2019-01-25 22:20 UTC
Searching for keyword  'United States of America' places the pin at 51.75693885,178.105906552159
this location is in Alaska. This is probably not the expected result when searching for those keywords

https://nominatim.openstreetmap.org/search.php?q=united+states+of+america&polygon_geojson=1&viewbox=

Search for keyword 'USA' gives result - 39.7837304,-100.4458825 
This is a location at the center of mainland United States. This the correct result

Can the search result for 'United States of America' be modified to give a location in mainland US?

**Comment by lonvia** [comment] 2019-01-26 10:56
The root cause is #543. We should remove the ways at least for admin_level < 4.

**Comment by lonvia** [comment] 2019-01-26 13:30
Fixed in c822012.

**Closed by lonvia** 2019-01-26 13:30 UTC
