### ISSUE TITLE
Haden Road, Houston not found

### ISSUE THREAD

**Issue by baerbock** [openstreetmap/Nominatim#1266] opened 2018-12-15 00:35 UTC
A search after [Haden Road, Houston](https://www.openstreetmap.org/search?query=Haden Road%2C Houston) is not delivering any results, despite the address is used [this way](https://www.reichhold.com/en/company-locations.aspx)

"[Haden Road, Harris County](https://nominatim.openstreetmap.org/search.php?q=Haden+Road%2C+Harris+County&polygon_geojson=1&viewbox=)" would work.

For the USA some sort of 'greater metro area' search must be implemented.

**Comment by pilyfond** [comment] 2018-12-15 00:47
I think this is related to https://github.com/openstreetmap/Nominatim/issues/1120

All incorporated suburbs of Greater Houston (Atascocita, Channelview, Cloverleaf, Crosby, Cypress, Fresno, Hockley, Klein, Port Bolivar, Spring, The Woodlands) should be found when searching after Houston.

**Comment by mtmail** [comment] 2018-12-15 00:51
The OSM data has Houston city boundaries. https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=2688911&class=boundary Those are usually imported from local GIS departments, I checked a couple of US cities in the past. The trouble is that those are often outdated and not even the local GIS departments update them.

It's tricky on the one hand to require the search to be strict and observe boundaries, then for other cities to ignore those.

There is no https://en.wikipedia.org/wiki/Greater_Houston in OSM data. Somebody needs to add that.

**Comment by lonvia** [comment] 2018-12-15 08:38
Duplicate of #1120.

**Closed by lonvia** 2018-12-15 08:38 UTC
