### ISSUE TITLE
Karlsruhe (city) not found using city= in structured query

### ISSUE THREAD

**Issue by fgenoese** [openstreetmap/Nominatim#1620] opened 2019-12-26 11:47 UTC
I would like to flag that the following query for the German city Karlsruhe (300k inhabitants) does not return any results for the city but only for a hamlet named Karlsruhe:
https://nominatim.openstreetmap.org/search.php?city=Karlsruhe&country=Germany

Interestingly, the alternative query does return the expected result:
https://nominatim.openstreetmap.org/search.php?q=Karlsruhe+Germany

**Comment by mtmail** [comment] 2019-12-26 19:57
The place node (https://www.openstreetmap.org/node/240120582) is a `place=city`, but the relation (https://www.openstreetmap.org/relation/62518) is tagged `admin_level=6` which is usually a county (German: Kreis oder kreisfreie Stadt) thus
https://nominatim.openstreetmap.org/search.php?county=Karlsruhe&country=Germany
works. Nominatim links both together (the node is a `role=label` of the relation) because they represent the same place and that's not always obvious and causes oddities when information is different between the two. Gets even more interesting when a place is both a city and a state (Hamburg, Berlin).
I need to check if we have a similar issue open.

**Comment by lonvia** [comment] 2019-12-27 09:57
Closing as duplicate of #774.

**Closed by lonvia** 2019-12-27 09:57 UTC
