### ISSUE TITLE
Place with correct city not found

### ISSUE THREAD

**Issue by JLuc** [openstreetmap/Nominatim#1246] opened 2018-11-25 08:31 UTC
`city=Die` in France doesnt lead to any result :-1: 
http://nominatim.openstreetmap.org/?city=DIE&limit=1&countrycodes=FR&format=json&accept-language=fr

But its `postalcolde=26150` returns it correctly :+1:
http://nominatim.openstreetmap.org/?postalcode=26150&limit=1&countrycodes=FR&format=json&accept-language=fr

Also when both stated :+1: https://nominatim.openstreetmap.org/?postalcode=26150&city=DIE+&limit=1&countrycodes=FR&format=json&accept-language=fr

First request should also bring result.

**Comment by lonvia** [comment] 2018-11-25 08:42
Duplicate of #1202.

**Closed by lonvia** 2018-11-25 08:42 UTC

**Comment by JLuc** [comment] 2018-11-25 08:57
Maybe the requested langage or the location langage should be taken into account before striping words
