### ISSUE TITLE
After installation shows broken UI.

### ISSUE THREAD

**Issue by Shourov7** [openstreetmap/Nominatim#880] opened 2018-01-10 08:35 UTC
After installation  in my pc nominatim shows broken UI. But if i want to search from it, it works but the UI of nominatim is broken. I repeat installation several time to fix this but it was not fixed. What I have to do?

![screenshot from 2018-01-10 14-26-28](https://user-images.githubusercontent.com/24294061/34762860-7d0c65dc-f613-11e7-96cb-75d17db9fbbf.png)

**Comment by lonvia** [comment] 2018-01-10 08:40
Duplicate of #872.

**Closed by lonvia** 2018-01-10 08:40 UTC
Labels: question
