### ISSUE TITLE
E. Golf Road in Schaumburg, IL only works with some addresses

### ISSUE THREAD

**Issue by kiler129** [openstreetmap/Nominatim#1182] opened 2018-09-17 21:09 UTC
## Overview
I found a problem, which I'm not sure if related to database or Nominatim. The address is `1227 E. Golf Rd., Schaumburg, IL, USA` (and [corresponds to a DMV gov. office](https://www.ilsos.gov/facilityfinder/facilityfinder?command=getFacilityDetails&facilityId=305)) and its geocode result is very skewed.

## Test Case
While attempting to geocode it the result is less than desired:
![image](https://user-images.githubusercontent.com/1227834/45649613-7887f380-ba91-11e8-9153-b6e2221d9ba0.png)
**Search:** https://nominatim.openstreetmap.org/search.php?q=1227+E.+Golf+Rd.%2C+Schaumburg%2C+IL%2C+USA
**Place:** https://nominatim.openstreetmap.org/details.php?place_id=99087793

When you try to put very similar address, which only differs by building number (`123 E. Golf Rd., Schaumburg, IL, USA`) the result is as expected:
![image](https://user-images.githubusercontent.com/1227834/45649873-3c08c780-ba92-11e8-81a5-8e2cb4466e48.png)
**Search:** https://nominatim.openstreetmap.org/search.php?q=123+E.+Golf+Rd.%2C+Schaumburg%2C+IL%2C+USA
**Place:** https://nominatim.openstreetmap.org/details.php?place_id=210891111

## Possible Source of the Problem
The first result can be improved by using `1227 Golf Rd., Schaumburg, IL, USA` (removed `E.` specifier). That way the result is correct like on Google Maps:
![image](https://user-images.githubusercontent.com/1227834/45650273-6a3ad700-ba93-11e8-86bd-b3582ab17ab3.png)
**Search:** https://nominatim.openstreetmap.org/search.php?q=1227+Golf+Rd.%2C+Schaumburg%2C+IL%2C+USA
**Place:** https://nominatim.openstreetmap.org/details.php?place_id=16472180

The address schema is rather weird there, and swings between `E. Golf Rd.` and `W. Golf Rd.`. OSM shows in that area `E. Golf Rd.` and `Golf Rd.`. It contains `W. Golf Rd.` too but in a different place and not chopped like GM does (which is actually correct):
![image](https://user-images.githubusercontent.com/1227834/45650432-e2a19800-ba93-11e8-9891-858f5886c371.png)
**Compare:** http://tools.geofabrik.de/mc/#15/42.0515/-87.9825&num=2&mt0=mapnik&mt1=google-map

Let me know if this I provided sufficient details. I will be happy to help.

**Comment by lonvia** [comment] 2018-09-18 20:10
Search should actually be fuzzy with respect to E/W/N/S in the US. At the moment it isn't so you need to give the exact street name as mapped in OSM or the search will fail most of the time. (There is a bit of searching partial terms but it does more harm than good in this case.)

Duplicate of #535, so closing here.

**Closed by lonvia** 2018-09-18 20:10 UTC

**Comment by kiler129** [comment] 2018-09-18 20:19
@lonvia So should I report the information inconsistency separately to OSM? Searching without N/E/S/W would a nice feature, however the information here are mismatched anyway ;)

**Comment by lonvia** [comment] 2018-09-18 20:38
If you have local knowledge that the street names are wrong in OSM, then you can directly fix them yourself or, if that is too time consuming, leave a note. See https://www.openstreetmap.org/fixthemap for more information. But please, don't copy such information from Google. Their information is copyrighted and therefore unusable for OSM (and in such case also not so seldomly wrong).

**Comment by kiler129** [comment] 2018-09-18 22:38
I do, I can see the street from a window right now. I checked on google to be sure it’s not some weird local thing we use, but in fact the street is officially overlord like that.

Thank you for the info!
