### ISSUE TITLE
bad search result when providing part of an object's name

### ISSUE THREAD

**Issue by notramo** [openstreetmap/Nominatim#743] opened 2017-06-04 17:46 UTC
Searching for ```tápióbicske pálinka``` gives no result. But searching for ```tápióbicske pálinkafőzde``` gives correct result. Nominatim should give these results for ```tápióbicske pálinka```.

search:
http://nominatim.openstreetmap.org/search.php?q=t%C3%A1pi%C3%B3bicske+p%C3%A1linka&polygon_geojson=1&viewbox=

Object I want to find:
https://www.openstreetmap.org/way/440988314

When providing a search term with an object's partial name, Nominatim should give the object in the results.

**Comment by lonvia** [comment] 2017-06-18 20:32
Duplicate of #145.

**Closed by lonvia** 2017-06-18 20:32 UTC
Labels: duplicate
