### ISSUE TITLE
GeoCodeJson Returns Strange Admin Data in Wiesbaden

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1275] opened 2019-01-04 13:58 UTC
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=50.040384&lon=8.213654&zoom=42&accept-language=en&addressdetails=1

yields
```
level2 | "Germany"
-- | --
level4 | "Rhineland-Palatinate"
level5 | "Regierungsbezirk Darmstadt"
level6 | "Wiesbaden"
level9 | "Mombach"
```

But Mombach is not within Wiesbaden on the OSM-Data as far as I can find. Mombach belongs to Mainz.

**Comment by txtor** [comment] 2019-10-24 14:31
This perhaps has to do with the way id 23746092 [0] which is near the location searched for and ends up in Mainz-Mombach [1]
[0] https://www.openstreetmap.org/way/23746092
[1] https://www.openstreetmap.org/relation/4555036

**Comment by mtmail** [comment] 2019-10-26 22:43
Pretty much. Long roads (OSM ways) aren't split at city boundaries during search time so it depends on where the center of the way is located.

**Comment by lonvia** [comment] 2019-10-28 21:18
That's a duplicate of #1400 then.

**Closed by lonvia** 2019-10-28 21:18 UTC
