### ISSUE TITLE
Make (electrical) substations searchable like industrial areas

### ISSUE THREAD

**Issue by sinanna** [openstreetmap/Nominatim#1072] opened 2018-06-22 10:21 UTC
@lonvia May you please make power=substation searchable the same way like landuse=industrial is already?

Because of the inability to search for named substations some users deliberately tag all of their substations as landuse=industrial ([https://www.openstreetmap.org/changeset/58643842]).

**Comment by lonvia** [comment] 2018-06-22 19:05
Duplicate of #523.

**Closed by lonvia** 2018-06-22 19:05 UTC
