### ISSUE TITLE
Countries don't have Parent Of section

### ISSUE THREAD

**Issue by siffash** [openstreetmap/Nominatim#1576] opened 2019-11-21 13:43 UTC
Nominatim, fresh installation on Ubuntu 18.04.3. Imported Africa from Geofabrik, set `import-admin.style` in the local settings file.
The details page for any country doesn't return country's children, the Parent Of section is missing. The cities & regions seem to be ok though.
The online version of Nominatim doesn't have this issue.

**Comment by mtmail** [comment] 2019-11-21 21:49
The details page is mostly used for debugging. Are there queries (forward or reverse) that don't return expected data? Or are you trying to build a new dataset by crawling the detail page content?

What does the following SQL query return? It should show many `boundary=administative` and/or `place=state` places.

```sql
select osm_type, osm_id, admin_level, class, type, name->'name'
from placex
where country_code='ke'
and parent_place_id=(select place_id from placex where osm_type='R' and osm_id=192798);
```
(That's Kenya https://www.openstreetmap.org/relation/192798)

**Comment by siffash** [comment] 2019-11-22 09:56
@mtmail I'm trying to build a new dataset by running sql queries. The first step is to return all countries, and the second is to find their child places. I'm stuck on the second one. The details page also shows no child places for countries.
The SQL query you provided returned 0 rows.

**Comment by lonvia** [comment] 2019-11-22 10:35
Has the import finished successfully? What does `select count(*) from placex where indexed_status > 0` report?

**Comment by siffash** [comment] 2019-11-22 11:00
@lonvia It returned 0.
The import finished successfully, and I tried to import several times, the outcome is the same every time. Also tried with Nominatim [downloaded from the website](https://nominatim.org/release/Nominatim-3.4.0.tar.bz2), as well as directly pulling Nominatim from Github (master branch).

**Comment by mtmail** [comment] 2019-11-22 18:18
I imported Kenya with admin style (took about 3min import time) and see the same

```sql
select count(*) from placex where country_code='ke';
  4268
```

```sql
select admin_level, count(*) from placex where country_code='ke' group by admin_level order by admin_level;
 admin_level | count
           2 |     2       // country
           3 |     8
           4 |    47     // state
           8 |     1      // city
           9 |     4
          10 |    22
          12 |     1
          15 |  4183
```

Meru, a state (admin_level=4, https://www.openstreetmap.org/relation/3495553) has East Kenya (admin_level=3, https://www.openstreetmap.org/relation/9724277) as parent.

East Kenya has no parent (no `parent_place_id`) set.

Not sure what the admin_level=3 places are. Wikipedia suggests pre-2013 provinces https://en.wikipedia.org/wiki/Provinces_of_Kenya#Former_provinces (In Nominatim:  Central, Central Kenya, Northeast Kenya, Coastal Kenya, East Kenya, West Kenya, Nyanza, Nairobi)

Country Kenya (https://www.openstreetmap.org/relation/192798) has no direct children
```sql
select count(*) from placex where parent_place_id=(select place_id from placex where osm_type='R' and osm_id=192798);
     0
```

**Comment by mtmail** [comment] 2019-11-22 18:24
@siffash If you only need country and state level you could try https://wambachers-osm.website/boundaries/ With right-click on a country you can select children, at the bottom you select data format and if you want the files separate or combined. Remember the new dataset would be under ODbL license https://opendatacommons.org/licenses/odbl/summary/ https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ

**Comment by siffash** [comment] 2019-11-22 18:40
@mtmail I will need all levels, not only countries & states.
If you check Kenya in the online version of Nominatim, you will see that it has children:
https://nominatim.openstreetmap.org/details.php?place_id=197669113
That's what I expect to see in Nominatim when I install it locally.

**Comment by mtmail** [comment] 2019-11-22 18:43
Understood. There is no timeline or estimate when this might be fixed.

**Comment by siffash** [comment] 2019-11-22 19:40
Would it be better to create an issue in [osm2pgsql](https://github.com/openstreetmap/osm2pgsql)? I assume the problem comes from there?

**Comment by lonvia** [comment] 2019-11-22 19:47
No. osm2pgsql has absolutely nothing to do with it.

Note that the `parent_place_id` (and consequently the `Parent Of` section in the debug view) is an internal implementation detail which might or not might get you what you want. This column is only used for rank 30 objects (POIs, housenumbers etc) to link to the parent street. For address hierarchies only the `address_placeline` table is relevant.

**Comment by lonvia** [comment] 2019-11-22 20:15
So this does not work because we have taken countries out of the hierarchy for efficiency reasons, see #1422. In that case you won't find it in the `address_placeline` either. States are the lowest level in the hierarchy.

Closing as 'it's a feature, not a bug'.

**Closed by lonvia** 2019-11-22 20:15 UTC

**Comment by siffash** [comment] 2019-11-23 09:39
@lonvia What would be the best way to extract the whole hierarchies of the places? Something like:
Country -> Region -> City/Town -> Neighborhood -> etc
I intended to return all countries first; then to find all places that have their ids as parent_place_id; then to find all places that have those ids as parent_place_id, and so on. This scenario is impossible now.

**Comment by mtmail** [comment] 2019-11-23 09:44
Please ask this question on http://help.openstreetmap.org/ Main purpose of Nominatim is searching for addresses, not extracting data. Nominatim might not be the right took for your project.

**Comment by siffash** [comment] 2019-11-23 10:02
@mtmail To be able to search for addresses you need hierarchies, that's exactly what I'm looking for. And Nominatim builds hierarchies very well.

**Comment by mtmail** [comment] 2019-11-23 10:03
It's a good side effect, but not something we offer support for.

**Comment by siffash** [comment] 2019-11-23 10:10
I'm not asking for a support. I'm asking for an advice of how this can be possibly done in most efficient way. I see that you don't know it too, so thank you anyway.
