### ISSUE TITLE
A simple search on London does not return London, England

### ISSUE THREAD

**Issue by rpezous** [openstreetmap/Nominatim#697] opened 2017-03-31 09:21 UTC
Hi all
thanks in advance for your support
When I do this very simple search
http://nominatim.openstreetmap.org/search?format=json&city=London
I do not get London, UK... I get only the one in North America...
I obviously miss something...

**Comment by mtmail** [comment] 2017-03-31 14:38
The simplest solution would be to use the `q=` parameter instead of `city=`

```
curl 'http://nominatim.openstreetmap.org/search?format=jsonv2&q=London' | jq '.[] | .display_name'
"London, Greater London, England, UK"
"London, Ontario, Canada"
"London, Laurel County, Kentucky, United States of America"
"London, Dane County, Wisconsin, United States of America"
"London, Madison County, Ohio, United States of America"
"London, Tulare County, California, United States of America"
"London, Pope County, Arkansas, United States of America"
"London, Kanawha County, West Virginia, United States of America"
"London, Mercer County, Pennsylvania, United States of America"
"London, Rusk County, Texas, United States of America"
```

**Comment by rpezous** [comment] 2017-03-31 15:20
thanks. very helpful 
I'm trying here to disambiguate cities coming from free text inputs ("NYC" or "newyork" or "new york").
 Should I expect any side effects switching to this other parameter?

thanks again

**Comment by cjgibson** [comment] 2017-03-31 15:27
If you know for a fact that you're working with global city names, a [fuzzy search against geonames.org](http://www.geonames.org/advanced-search.html?q=newyork&country=&featureClass=P&continentCode=&fuzzy=0.6) may provide better results.

**Comment by lonvia** [comment] 2017-10-10 21:13
Duplicate of #774.

**Closed by lonvia** 2017-10-10 21:13 UTC
