### ISSUE TITLE
St Patrick cathedral is not found if you don't write the exact informations

### ISSUE THREAD

**Issue by LAfricain** [openstreetmap/Nominatim#1489] opened 2019-09-06 15:57 UTC
I would like to found : [St Patrick NY city Cathedral](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=40.72998%2C-73.99406%3B40.75856%2C-73.97636#map=14/40.7448/-73.9803)
But if I wrote St Patrick NY, it sends me in [Toronto](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=40.7300%2C-73.9941%3B43.6548%2C-79.3883#map=7/42.205/-76.898)
I need to wrote exactly St Patrick's cathedral.

**Comment by mtmail** [comment] 2019-09-06 16:01
Nominatim requires all words of the name to be present in the query, here "St. Patrick's Cathedral" https://www.openstreetmap.org/way/266010379

If you think people in New York usually use a different name for the cathedral you can add an `alt_name` https://wiki.openstreetmap.org/w/index.php?title=Key:name&uselang=en-US

**Comment by LAfricain** [comment] 2019-09-06 16:04
> Nominatim requires all words of the name to be present in the query, here "St. Patrick's Cathedral" 

I'm not English speaker, I tried on Google Map and it could find it. Probably it accepts a margin of error in the name.

**Comment by lonvia** [comment] 2019-10-19 14:59
Duplicate of #244.

**Closed by lonvia** 2019-10-19 14:59 UTC
Labels: data issue
