### ISSUE TITLE
highway:bus node match is preferred over an exact street

### ISSUE THREAD

**Issue by zoharby** [openstreetmap/Nominatim#901] opened 2018-01-31 08:15 UTC
The following reverse geocoding query:
https://nominatim.openstreetmap.org/search.php?q=32.17475%2C34.86981&polygon_geojson=1&viewbox=
Should result in "Shai Agnon" street (way [24834125](https://www.openstreetmap.org/way/24834125)) on which it falls right on, but instead results in a match to a further away bus stop "Ben Gurion/Pardes Meshutaf" (node [1802999869](https://www.openstreetmap.org/node/1802999869)), and hence the address is wrongly returned as "Ben Gurion" street.
Looks like the bus stop is wrongly preferred over the correct street.

**Comment by lonvia** [comment] 2018-01-31 08:35
Duplicate of #892. More discussion on how and why reverse works as it is in #512.

**Closed by lonvia** 2018-01-31 08:35 UTC
Labels: Reverse, duplicate, wontfix
