### ISSUE TITLE
Missing City_district (admin level 9) on zoom 14 and higher

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#831] opened 2017-10-25 17:02 UTC
Example
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=52.1022876368&lon=13.3744812012&zoom=14&format=xml

Not happend in former times

**Comment by lonvia** [comment] 2017-10-27 20:30
Duplicate of #764.

Nothing has changed in the algorithm for years. If it has changed, then the OSM data has changed.

**Closed by lonvia** 2017-10-27 20:30 UTC
