### ISSUE TITLE
User context has no effect

### ISSUE THREAD

**Issue by gagarine** [openstreetmap/Nominatim#1407] opened 2019-06-21 17:28 UTC
Search on OSS is painful as it seem to not take into account my context.

The map is open at https://www.openstreetmap.org/search?query=3dd#map=19/46.19680/6.14703 (Geneva Switzerland)

I'm searching for "3dd"

I'm moved km away at https://www.openstreetmap.org/search?query=3dd#map=19/52.87366/-1.49135 and the search result is all about place in UK
![Screenshot 2019-06-21 at 19 21 54](https://user-images.githubusercontent.com/164074/59940038-ebc3f900-9459-11e9-94ce-0838b21a9099.png)

What I actually want is https://www.openstreetmap.org/node/6563385577 "3DD espace de concertation"

How I'm supposed to find places?

**Comment by mtmail** [comment] 2019-06-22 01:00
Proximity or user context won't help with this query. Nominatim can't search for subphrases of names. 

If the place is also known as "3DD" you can add a `short_name` to the place. Or maybe "3DD" is the main name people refer to then use it as `name` and add the longer name as `official_name`.

https://wiki.openstreetmap.org/w/index.php?title=Key:name

**Comment by lonvia** [comment] 2019-06-22 13:41
Duplicate of #244.

**Closed by lonvia** 2019-06-22 13:41 UTC
