### ISSUE TITLE
Bad whole street polygon

### ISSUE THREAD

**Issue by howardEagle** [openstreetmap/Nominatim#666] opened 2017-03-17 13:57 UTC
http://nominatim.openstreetmap.org/search.php?q=%D0%9A%D0%BE%D1%86%D1%8E%D0%B1%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82+%D0%92%D1%96%D0%BD%D0%BD%D0%B8%D1%86%D1%8F&polygon=1

Why is whole street cannot be selected?

**Comment by lonvia** [comment] 2017-03-17 21:14
The street is segmented in the OSM data. Nominatim is currently not able to join multiple ways.

Duplicate of #114.

**Closed by lonvia** 2017-03-17 21:14 UTC
Labels: duplicate
