### ISSUE TITLE
Searching 'bakewell' does not return 'bakewell CP'

### ISSUE THREAD

**Issue by jolyonralph** [openstreetmap/Nominatim#1409] opened 2019-06-26 10:35 UTC
When searching for civil parishes in the UK the search has to explicitly add CP or the search result is not returned.

For example, searching for 'bakewell' and limiting results to regions with boundaries returns no results, even though Bakewell CP should match and does have a boundary. 

Change the search to 'bakewell cp' and the correct result is shown.

There are many other examples wordwide where if the exact format of the political region is not known you have no hope of finding it within nominatim. 

Perhaps there is a way of doing a *bakewell* style search, but if there is it's not obvious.

**Comment by lonvia** [comment] 2019-06-26 10:39
See https://github.com/openstreetmap/Nominatim/issues/94#issuecomment-31442894

**Comment by SomeoneElseOSM** [comment] 2019-06-26 10:56
(for the avoidance of doubt) just searching for "bakewell" without any restrictions returns the town of Bakewell, which I'd say was correct.  That object is the admin_centre of the "Bakewell CP" relation, so it's not hard to find.
Somewhat offtopic for Nominatim but relevant to OSM naming is whether "... CP" makes sense on the name here.  I'd suggest it does - in quite a few cases the administrative area isn't what you'd expect based on the name (e.g. https://www.openstreetmap.org/search?whereami=1&query=53.4792%2C-1.7927#map=16/53.4785/-1.7904 is still "in Sheffield" even though it's northwest of Ladybower).

**Comment by lonvia** [comment] 2019-06-26 19:37
To add to that "Bakewell CP" will eventually show up if you click "More results" often enough. Problem is that apparently Bakewell is just such a popular name for cafes and such and they are returned first. This certainly is a problem and could be done better but the issue is already covered by #94 and #244. So closing here as duplicate.

**Closed by lonvia** 2019-06-26 19:37 UTC

**Comment by jolyonralph** [comment] 2019-07-04 07:50
The problem isn't what is returned as the first result (and I'd agree that bakewell town should be the primary result), it's that when I am searching for a political region named X in a country somewhere, I have to know exactly what format that political region is stored in OSM or I don't find it. 

For those who come across this thread, the way I have found to solve it so far (which is a horrendous hack) is to find the region page on Wikipedia, check to see if there is a wikidata entry and if that's linked to OSM then perfect. Otherwise if there isn't, I take the full local language name of the political region in Wikipedia and use that to search which is generally more reliable.
