### ISSUE TITLE
Missing results when searching by query-parameters "city" and "country" (e.g. city=Bremen&country=DE)

### ISSUE THREAD

**Issue by Wackanabel** [openstreetmap/Nominatim#860] opened 2017-12-03 14:29 UTC
When I use the Nominatim Web-GUI to search "Bremen" I get the expected/desired result "Bremen, Deutschland (City)".

https://nominatim.openstreetmap.org/search.php?q=bremen&polygon_geojson=1

When I use the REST-API for the search "Bremen, Deutschland (City)" is not included in the results. I only retrieve the following results:

- Bremen, Verwaltungsgemeinschaft Wangen im Allgäu, Landkreis Ravensburg, Regierungsbezirk Tübingen, Baden-Württemberg, 88279, Deutschland
- Bremen, Kreis Soest, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 59469, Deutschland
- Bremen, Rheinisch-Bergischer Kreis, Regierungsbezirk Köln, Nordrhein-Westfalen, 42929, Deutschland
... 5 others

The relating REST-CALL is:

GET http://nominatim.openstreetmap.org/search?city=Bremen&country=DE&limit=50&format=json&polygon_geojson=1

I could identify the same problem for the following german cities: München, Nürnberg, Bochum, Bielefeld, Karlsruhe, Augsburg, Gelsenkirchen, Krefeld and Kassel

**Comment by lonvia** [comment] 2017-12-14 21:58
Duplicate of #774.

**Closed by lonvia** 2017-12-14 21:58 UTC
Labels: duplicate, Search
