### ISSUE TITLE
./utils/update.php --init-updates  fails with "osmium.cpython-34m.so: undefined symbol:" error

### ISSUE THREAD

**Issue by GKurt** [openstreetmap/Nominatim#1167] opened 2018-09-07 20:27 UTC
Hello,
     I'm seeing the above error when trying to initialize updates via pyosmium. The full error line is:

ImportError: /usr/lib64/python3.4/site-packages/osmium/_osmium.cpython-34m.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE 

     This is the full output:
[nominatim@web3 build]$ ./utils/update.php --init-updates
Traceback (most recent call last):
  File "/bin/pyosmium-get-changes", line 22, in <module>
    from osmium.replication import server as rserv
  File "/usr/lib64/python3.4/site-packages/osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: /usr/lib64/python3.4/site-packages/osmium/_osmium.cpython-34m.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
Cannot execute pyosmium-get-changes.
Make sure you have pyosmium installed correctly
and have set up CONST_Pyosmium_Binary to point to pyosmium-get-changes.
ERROR: pyosmium-get-changes not found or not usable
pyosmium-get-changes not found or not usable
[nominatim@web3 build]$

     I did install osmium:

[nominatim@web3 build]$ pip3 list
Package        Version
-------------- -------
behave         1.2.6  
nominatim      0.1    
nose           1.3.7  
osmium         2.14.3 
parse          1.8.4  
parse-type     0.4.2  
pip            18.0   
pytidylib      0.3.2  
setuptools     19.6.2 
setuptools-scm 1.10.1 
six            1.11.0 
[nominatim@web3 build]$

**Comment by GKurt** [comment] 2018-09-07 20:41
There seems to be a size limit in the issue, so here is more problem description:

    In ./settings/local.php I have:

[nominatim@web3 build]$ cat settings/local.php
<?php
@define('CONST_Database_Web_User', 'apache');
@define('CONST_Website_BaseURL', '/nominatim/');
@define('CONST_Osm2pgsql_Flatnode_File', '/home/nominatim/build/flatnode.file');
@define('CONST_Pyosmium_Binary', '/bin/pyosmium-get-changes');
[nominatim@web3 build]$

     The configuration info requested in the posting guidelines is as follows:

CPU:        Intel(R) Pentium(R) CPU G4400 @ 3.30GHz , 2 Cores
RAM:        32 GB
DISK:       4 x 1TB, Raid 5 via md/lvm
OS:         CentOS Linux release 7.5.1804 (Core)
Postgresql: 10.5.1 from www.postgresql.org pgdg10 repository
PostGIS:    2.4.4-2 from www.postgersql.org pgdg10 repository
postgresql.conf changes:
shared_buffers = 2GB                    # min 128kB
work_mem = 50MB                         # min 64kB
maintenance_work_mem = 10GB             # min 1MB
fsync = off                             # flush data to disk for crash safety
synchronous_commit = off                # synchronization level;
full_page_writes = off
checkpoint_timeout = 10min              # range 30s-1d
checkpoint_completion_target = 0.9      # checkpoint target duration, 0.0 - 1.0
effective_cache_size = 24GB
nominatim: Nominatim-3.2.0

     Any assistance would be most appreciated.

**Comment by GKurt** [comment] 2018-09-07 20:47
[nominatim@web3 build]$ cat settings/local.php
<<?php
@define('CONST_Database_Web_User', 'apache');
@define('CONST_Website_BaseURL', '/nominatim/');
@define('CONST_Osm2pgsql_Flatnode_File', '/home/nominatim/build/flatnode.file');
@define('CONST_Pyosmium_Binary', '/bin/pyosmium-get-changes');
[nominatim@web3 build]$>

**Comment by GKurt** [comment] 2018-09-07 20:48
CPU:        Intel(R) Pentium(R) CPU G4400 @ 3.30GHz , 2 Cores
RAM:        32 GB
DISK:       4 x 1TB, Raid 5 via md/lvm
OS:         CentOS Linux release 7.5.1804 (Core)
Postgresql: 10.5.1 from www.postgresql.org pgdg10 repository
PostGIS:    2.4.4-2 from www.postgersql.org pgdg10 repository
postgresql.conf changes:
shared_buffers = 2GB                    # min 128kB
work_mem = 50MB                         # min 64kB
maintenance_work_mem = 10GB             # min 1MB
fsync = off                             # flush data to disk for crash safety
synchronous_commit = off                # synchronization level;
full_page_writes = off
checkpoint_timeout = 10min              # range 30s-1d
checkpoint_completion_target = 0.9      # checkpoint target duration, 0.0 - 1.0
effective_cache_size = 24GB
nominatim: Nominatim-3.2.0
Any assistance would be most appreciated.

**Comment by Dmitry15** [comment] 2018-09-10 03:05
CentOS 7.2 and Nominatim 3.2.

**Comment by mtmail** [comment] 2018-09-10 13:01
The root cause is a version mismatch between the system-wide installed libboost library and python. (thx @lonvia for pointers)

https://github.com/osmcode/pyosmium/issues/33
https://github.com/osmcode/pyosmium/issues/52
https://github.com/osmcode/pyosmium/issues/56
have more details. Closing here.

**Closed by mtmail** 2018-09-10 13:01 UTC

**Comment by GKurt** [comment] 2018-09-14 17:07
@Dmitry15 I was able to get the .osm file update process working. I had to build my own version of libboost_python.so, and before doing so I had to make various ‘quick-and-dirty’-type changes to persuade the libboost build process to reference python3 instead of python. There is probably a ‘right’ way to do this that requires more knowledge than I have time to acquire about the bjam/b2 build ecosystem that the boost project uses.

This worked for me on Centos 7.5.1804. I think “yum update” will bring any earlier Centos 7 release up to that.

First get the latest boost source, currently 1.68.0, and unpack:

wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
gunzip -c boost_1_68_0.tar.gz | tar xvf -
cd boost_1_68_0/

The regular build process (well-documented on their website)  to make the boost python and some other libraries and install then in /usr/local is:

 ./bootstrap.sh --prefix=/usr/local --exec-prefix=/usr/local --with-librares=filesystem,system,python,mpi
  ./b2
  ./b2 install
But this will make use of the default python for Centos 7, which is python2, and the resulting library will not have the _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE symbol defined in it. The “quick-and-dirty” workaround is to delete and recreate “python” symlinks to point to “python3” instead of “python2”:

root: which python
/bin/python
root: cd /bin
root: ls -l python*
lrwxrwxrwx. 1 root root     7 Sep 13 15:03 python -> python2
lrwxrwxrwx. 1 root root     9 Aug 23 14:50 python2 -> python2.7
-rwxr-xr-x. 1 root root  7216 Jul 13 09:07 python2.7
.  .  .  .  .  .
lrwxrwxrwx. 1 root root     9 Sep  6 13:33 python3 -> python3.4
-rwxr-xr-x. 2 root root 11392 Aug 14 17:31 python3.4
.  .  .  .  .  . 
root: unlink python
root: ln -s python3 python
root:

**Comment by GKurt** [comment] 2018-09-14 17:15
@Dmitry15 If your “python” binary is elsewhere you may have to so this a little differently. This change persuades the bootstrap/b2  process to use and build for python3, but it wants to find various python3 include files in “/usr/include/python3.4”, and my system had no such directory. I created it as follows:

root: cd /usr/include
root: ls -ld *python*
drwxr-xr-x. 2 root root 4096 Aug 23 14:51 python2.7
drwxr-xr-x. 2 root root 4096 Aug 23 14:52 python2.7-debug
drwxr-xr-x. 2 root root 4096 Sep  6 13:33 python3.4d
drwxr-xr-x. 2 root root 4096 Sep  6 13:33 python3.4m
root: ln -s python3.4m/ python3.4
root:

After this, the regular build process above created a library in /usr/local/lib that has the required symbol table entry:

root: cd /usr/local/lib
root: ls -l "*python*"
-rw-r--r--. 1 root root 604620 Sep 13 14:55 libboost_python34.a
lrwxrwxrwx. 1 root root     27 Sep 13 14:55 libboost_python34.so -> libboost_python34.so.1.68.0
-rwxr-xr-x. 1 root root 365360 Sep 13 14:55 libboost_python34.so.1.68.0
root: nm -D libboost_python34.so |  \
  grep _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
000000000002df50 T _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
root:

There are a lot of Centos system programs that expect the default ‘python’ binary to be a python2 version, so you should put it back after this. I think the include directory symlink can stay.

After these changes I deleted the ~nominatim/build directory, and added “/usr/local/lib” to the LD_LIBRARY_PATH environment variable, and then re-did the Nominatim installation process and data download as described at http://nominatim.org/release-docs/latest/admin/Installation/ .

After that, the  “./utils/update.php –init-updates” command ran successfully for me.

Also, I had to change the interpreter (the first line) of:

                    ~nominatim/Nominatim-3.2.0/utils/osm_file_date.py

from “#!/usr/bin/python” to “#!/usr/bin/python3” to get the continuous update command:

./utils/update.php --import-osmosis-all

to work. It was erroring out, saying it could not find the “osmium” module.

**Comment by Dmitry15** [comment] 2018-09-14 19:03
@GKurt Thank you very much for the instructions. I will try.
