### ISSUE TITLE
Different result when changing limit parameter

### ISSUE THREAD

**Issue by hanskuiters** [openstreetmap/Nominatim#975] opened 2018-03-15 15:34 UTC
I have this query:
http://nominatim.openstreetmap.org/?q=onderlangs+1,arnhem,6812CE&format=json&addressdetails=0&limit=1&osm_type=N

That gives me an address in Braamt. This is not the wanted location.

If I use this query I get two results, the first result the one I want, an address in Arhem.
http://nominatim.openstreetmap.org/?q=onderlangs+1,arnhem,6812CE&format=json&addressdetails=0&limit=4&osm_type=N

Notice that the result from the first query, Braamt, is not in the second query. Both cities are in The Netherlands. I can't figure out why. What am I missing here?

**Comment by lonvia** [comment] 2018-03-15 15:36
Duplicate of #882.

**Closed by lonvia** 2018-03-15 15:36 UTC
