### ISSUE TITLE
Incorrect address location on OpenStreet

### ISSUE THREAD

**Issue by werck1** [openstreetmap/Nominatim#727] opened 2017-05-20 01:46 UTC
OpenStreet Map has my home positioned at the wrong location on its map.  The below link is the correct location of 9515 Berwick St., St. Louis, MO 63123 as shown on Google Maps.

https://www.google.com/maps/place/9515+Berwick+Dr,+Affton,+MO+63123/@38.5472669,-90.3316861,17z/data=!4m5!3m4!1s0x87d8c9a207ad80a9:0xc69ce1a9bdb89f0a!8m2!3d38.547418!4d-90.332008?hl=en

**Comment by juanmaneo** [comment] 2017-05-22 14:46
I have incorrect address too: 

I enter coordinate 47.7869164517,8.5678526759 in Germany near frontier.

http://nominatim.openstreetmap.org/search.php?q=47.7869164517%2C8.5678526759&polygon_geojson=1&viewbox=


But the coordinate are transformed to 47.7921077,8.571674 so it gives me Switzerland instead of Germany.

http://nominatim.openstreetmap.org/details.php?place_id=127336933


see: 

https://www.google.fr/maps/place/47%C2%B047'12.9%22N+8%C2%B034'04.3%22E/@47.7859794,8.5638938,16z/data=!4m5!3m4!1s0x0:0x0!8m2!3d47.7869165!4d8.5678527?hl=en

https://yandex.fr/maps/?mode=search&text=47.7869164517%2C8.5678526759&sll=2.341198%2C48.856929&sspn=0.494728%2C0.191657

**Comment by mtmail** [comment] 2017-05-22 14:49
@juanmaneo Please open a new issue with your example. The issue is unrelated to a missing street number in the United States.

**Comment by juanmaneo** [comment] 2017-05-22 15:22
@mtmail  Thanks, new issue  #729

**Comment by SrihariThalla** [comment] 2017-05-24 10:09
It seems it is Berwick Drive and not Street. 

@mtmail Seems it's the Tiger data that has the wrong house? OpenAddresses seems to have it correctly ([Link](https://mapzen.com/products/search/?query=9515%20Berwick%20Dr%2C%20Affton%2C%20MO%2C%20USA&endpoint=place&gid=openaddresses%3Aaddress%3Aus%2Fmo%2Fst_louis%3A4ad6bd542d8af136&selectedLat=38.54743&selectedLng=-90.33199&lng=-90.33101&lat=38.54757&zoom=18)) !

**Comment by lonvia** [comment] 2017-05-24 20:00
This address is not yet in OpenStreetMap. The good news is that you can fix this problem yourself. Please see http://www.openstreetmap.org/fixthemap for information how to contribute to OpenStreetMap and add your address to the database.

Closing as this is not an issue with Nominatim directly.

**Closed by lonvia** 2017-05-24 20:00 UTC
Labels: data issue

**Comment by Keoth24** [comment] 2024-09-26 17:44
My address is showing wrong on the map  how do I get this changes
