### ISSUE TITLE
wrong results when not using city sufix

### ISSUE THREAD

**Issue by geoneutrino** [openstreetmap/Nominatim#1438] opened 2019-07-24 13:05 UTC
in Freiberg south germany
geocoding with streets results in bad results when not using the suffix "am Neckar"
e.g.
https://www.openstreetmap.org/search?query=Holbeinstra%C3%9Fe%2C%2071691%20Freiberg#map=9/47.6300/9.4046
or "Holbeinstraße Freiberg" without zip jumps to Freiburg (same street name, different city name) 100km away

when using Street+Zip it works
https://www.openstreetmap.org/search?query=holbeinstraße 71691

same applies for other streets ind the surrounding

but community mapping of the citypart maps the name without the suffix, so both ways should be accepted as used by people ? 
https://www.openstreetmap.org/relation/1107797
Especially when in Germany and Austria there are many names with region suffix this can happen in other scenarios too ...

**Comment by lonvia** [comment] 2019-07-25 21:26
Duplicate of #244 (see [issue comment](https://github.com/openstreetmap/Nominatim/issues/244#issuecomment-76477045)).

To make clear that something is a suffix  (quite hard to guess for a machine) use short_name for the city name without the suffix.

**Closed by lonvia** 2019-07-25 21:26 UTC
