### ISSUE TITLE
Entire Zip Code/City Does Not Display

### ISSUE THREAD

**Issue by sun-raven** [openstreetmap/Nominatim#752] opened 2017-06-11 23:54 UTC
I have a booking software that uses your mapping but I cannot get any combination of zip code 05495 (Williston, Vermont) to display.....I have tried other addresses (trying to input 426 Industrial Ave.) and different combinations of with and without zip code. Other locations in other towns seem to work.
![screen shot 2017-06-11 at 7 53 35 pm](https://user-images.githubusercontent.com/29361638/27015597-b7fe3da4-4edf-11e7-80af-0a6e6378d690.png)

**Comment by lonvia** [comment] 2017-06-12 15:02
Due to #746, postcode lookup is currently a bit patchy on nominatim.osm.org. The US should be mostly okay again by now, though.

The particular street from your example cannot be found because there is a typo in the OpenStreetMap data, it is called ['Industrial Avnue'](http://www.openstreetmap.org/way/370435188) there. This needs to be [fixed in OpenStreetMap directly](http://www.openstreetmap.org/fixthemap).

Closing as duplicate of #750.

**Closed by lonvia** 2017-06-12 15:02 UTC
Labels: data issue, duplicate

**Comment by sun-raven** [comment] 2017-06-12 16:25
Sorry but the entire 05495 zip code as I mentioned in the support ticket are not searchable. Other addresses as well. 


On June 12, 2017 at 11:02:17 AM, Sarah Hoffmann (notifications@github.com) wrote:

Due to #746, postcode lookup is currently a bit patchy on nominatim.osm.org. The US should be mostly okay again by now, though.

The particular street from your example cannot be found because there is a typo in the OpenStreetMap data, it is called 'Industrial Avnue' there. This needs to be fixed in OpenStreetMap directly.

Closing as duplicate of #750.
