### ISSUE TITLE
utils/update.php osm2pgsql --number-processes 1

### ISSUE THREAD

**Issue by shallot** [openstreetmap/Nominatim#957] opened 2018-03-01 08:43 UTC
Hi,

How come this is hardcoded to 1 in `$sOsm2pgsqlCmd`?

Would it make sense to set it to `$aResult['index-instances']`?

TIA

**Comment by lonvia** [comment] 2018-03-01 09:15
Duplicate of #917.

**Closed by lonvia** 2018-03-01 09:15 UTC
