### ISSUE TITLE
Cannot geocoding with nameaddress_vector candidate.

### ISSUE THREAD

**Issue by Emil-Zhou** [openstreetmap/Nominatim#1367] opened 2019-04-26 07:19 UTC
Hi here,

I have a testing address for Geocoding but without result:
`14762 Washington Ave, Apt. 222,94578` [link](https://nominatim.openstreetmap.org/search.php?q=14762+Washington+Ave%2C+Apt.+222%2C94578&polygon_geojson=1&viewbox=)

I did some tests and found that it caused by `Apt. 222`, this address can be location after removing the sentence `Apt. 222`:
`14762 Washington Ave, 94578` [link](https://nominatim.openstreetmap.org/search.php?q=14762+Washington+Ave%2C+94578&polygon_geojson=1&viewbox=)

Ok, here is my debugging:

1. I got the following debug information with `14762 Washington Ave, Apt. 222,94578` :
Here is a search candidate with Address Tokens:"#apt(794998)#, #222(662824)#" and the SQL will append "and nameaddress_vector @> ARRAY[794998,662824]". And there is no result for it
![image](https://user-images.githubusercontent.com/16344877/56788432-0b5fec00-6832-11e9-82a5-406e32f9563e.png)

2. For the address without "Apt. 222", there is a search candidate without Address Tokens , and it returns some PlaceIds then we can get the address location.
![image](https://user-images.githubusercontent.com/16344877/56788901-31d25700-6833-11e9-8032-0b02caf00fb9.png)

And I found there is no search candidate in #2 (without Address Tokens) for `14762 Washington Ave, Apt. 222,94578` :

So far as i understand the code, can we add the search candidate without Address Tokens to the search candidates? Method 'getGroupedSearches'?

Thanks,
Emil

**Comment by lonvia** [comment] 2019-04-26 07:39
Nominatim expects that all terms in your query match in the result. That is not going to change any time soon.

Duplicate of #145 and #587.

**Closed by lonvia** 2019-04-26 07:39 UTC
