### ISSUE TITLE
Incorrect town name handling at lower zoom levels

### ISSUE THREAD

**Issue by gopi-ar** [openstreetmap/Nominatim#1094] opened 2018-07-16 07:45 UTC
#1054 is a great update! I was going to post a fix to make the number of loops in the old logic configurable so it doesn't slow down requests in rural areas / oceans as much, but this approach is better.

One issue this doesn't fix though is how town / city names are handled at  lower (z13+) zoom levels. 

For e.g., here's a request in `Albertville, USA` at z18:
[Albertville, z18](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=34.23118161983776&lon=-86.16238230889306&zoom=18). It ends up taking the `town` name from the highway, which originates in `Boaz`.

Here's the same lat/lon at z13:
[Albertville, z13](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=34.231181619838&lon=-86.162382308893&zoom=13). This returns the correct city name.

I understand polygon lookups are probably too expensive or incomplete in OSM, but Photon gets this [same result right without using polygons](http://photon.komoot.de/reverse?lat=34.231181619838&lon=-86.162382308893). I saw that its importer maps each place_id to all parent_ids for each row to get a proper hierarchy and might also be a bit expensive for nominatim to do real-time.

@lonvia If there's a way to fix this without regressing on performance, happy to send a PR.

**Comment by lonvia** [comment] 2018-07-17 20:09
Duplicate of #328.

Note that Photon doesn't get it right, it just returns a result that is further away but completely within Boaz.

**Closed by lonvia** 2018-07-17 20:09 UTC
