### ISSUE TITLE
more priority for local for some categories 

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#1685] opened 2020-02-18 08:22 UTC
Currently, if you search without location reference, you get arbitrary results (e.g. if I search for “Ilios” from mobile and being in Rome, I get 11 results in Germany, Greece and other countries, prior to getting the Greek restaurant in Rome (fast food tagged). ). IMHO local must get more priority over typology (if the question is between supermarket, restaurant and fast food, which all are only of local interest). Also searches for “fuel”, “petrol station” don’t yield any reasonable results nearby, just arbitrary results somewhere on the globe. The same applies to road name searches without a city.

**Comment by lonvia** [comment] 2020-02-18 19:35
I'm sorry but I'm confused. How exactly is Nominatim supposed to know you are in Rome when you don't give it a location reference? I just tried your search for ['Ilios' somewhere in Rome](https://nominatim.openstreetmap.org/search.php?q=Ilios&polygon_geojson=1&viewbox=12.27997%2C41.94187%2C12.74517%2C41.81406) and your Greek restaurant shows up first.

**Comment by dieterdreist** [comment] 2020-02-18 21:36
I was looking at the map with my position centered, about 2km away from the restaurant, in zoom 18 (this is the default when you click the locate me button on OpenStreetMap.org).
I have now tested this more, and when the place is within the visible map portion it is found as expected.
For local searches (i.e. restaurants, shops, fuel, basically everything without a location information like city, region or country), reasonable defaults could be 10, 20 or 50km. The visible map will typically be something like 200x200m after using the location button (z18), i.e. it should be expanded.
Almost nobody will be interested in a restaurant in Athens, Germany or the US when she’s in Italy, even less in gas stations (when doing the generic search)

**Comment by lonvia** [comment] 2020-02-18 21:42
Duplicate of #824.

**Closed by lonvia** 2020-02-18 21:42 UTC
