### ISSUE TITLE
Short name displayed and given higher priority in search results

### ISSUE THREAD

**Issue by fqdb** [openstreetmap/Nominatim#891] opened 2018-01-22 08:42 UTC
Apparently recently Nominatim has started preferring short names (short_name:en) 
in the search results and for displaying names. For some reason, in case of China, this has produced an issue, whereas for the UK, it works as preferred.

If you search 'China', a town in Mexico is now the top result:

![image](https://user-images.githubusercontent.com/2826336/35211650-a5f625b2-ff57-11e7-88c6-26b6400ac506.png)

Using a search link without any map view and all cookies cleared, the top result becomes a locality in Spain: www.openstreetmap.org/search?query=china

The second issue is that if you get the country as a result, it always shows the result as 'PRC', not as 'People's Republic of China', but in case of the UK, it is always shown as 'United Kingdom'. Maybe this lies on the end of the tags in the OSM database, in which case, please explain in what way the tags should be altered to provide a consistent result.

The short names for China seem to be added in this changeset, but it didn't touch the normal name:en entry. https://www.openstreetmap.org/changeset/55198976

**Comment by lonvia** [comment] 2018-01-22 09:09
Duplicate of #783.

The tag causing difficulties here is short_name:en (note that the UK only has a short_name tag.)

Nominiatim has not changed its algorithm. Mappers have just started misusing short_name for random abbreviations. I guess I have do something about it eventually on the Nominatim side but for a data consumer it is extremely annoying when mappers change the meaning of a tag like that.

**Closed by lonvia** 2018-01-22 09:09 UTC

**Comment by fqdb** [comment] 2018-01-22 09:30
Thank you, I will remove the short_name tags on OSM.
