### ISSUE TITLE
tigerAddressImport.py not found

### ISSUE THREAD

**Issue by Emil-Zhou** [openstreetmap/Nominatim#1364] opened 2019-04-24 07:43 UTC
Hi Dear Nominatim Team
Here is an issue about  "sh: 1: /srv/nominatim/Nominatim-3.2.0/utils/tigerAddressImprt.py: not found" when importing the original TIGER2018 data.

![image](https://user-images.githubusercontent.com/16344877/56637354-066a3380-669e-11e9-96c9-5f27505d35ff.png)

Any suggestion would be greatly appreciated!

Here is the details on my side:

1. Install information
  - Ubuntu 18.04.2
  - Install Nominatim following the doc "[Installation on Ubuntu 18](http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/)"
  - Import the Database following the doc "[Importing and Updating](http://nominatim.org/release-docs/latest/admin/Import-and-Update/)", including "Wikipedia rankings", "UK postcodes" and "Initial import of the data"
  - "process the data from the original TIGER data to create the SQL", the exception occurred at this step
       a. Download **TIGER2018** EDGES files from Census.
       b. Put the files into a folder "/srv/nominatim/Nominatim-3.2.0/data/tigerEDGES" and run the command as: 
`sudo ./utils/imports.php --parse-tiger /srv/nominatim/Nominatim-3.2.0/data/tigerEDGES`
and it will print the following information as the above screenshot.
       c. The tiger folder "/srv/nominatim/Nominatim-3.2.0/data/tiger" is still empty

2. Some debug on my side

- The file "tigerAddressImport.py" is in the specified path
![image](https://user-images.githubusercontent.com/16344877/56637524-737dc900-669e-11e9-9a9c-3d93103fc30a.png)

Thanks,
Emil

**Comment by mtmail** [comment] 2019-04-24 10:15
I'm staring at the screenshots, but can't see any typo or mistake either.

The TIGER data processing is two steps (1.) parse, which converts *.zip files into *.sql files and (2.) import. http://nominatim.org/release-docs/latest/admin/Import-and-Update/

You can skip the parse when you just download the pre-parsed files. The documentation still talks about 2017 data, but 2018 data exists on https://nominatim.org/data/ US Census hasn't released 2019 data yet.

**Comment by lonvia** [comment] 2019-04-24 11:11
Looks like python might be missing. Can you check if there is a `/usr/bin/python` and what `which python` says?

**Comment by Emil-Zhou** [comment] 2019-04-25 10:02
Thanks Guys,

I'll try to import Tiger 2018 which Nominatim preprocessed. Thanks again!

by the way, I checked the `/usr/bin/python`:

![image](https://user-images.githubusercontent.com/16344877/56726855-27a45000-6782-11e9-802a-678c970b0ff2.png)


And Nominatim is amazing.


Emil

**Comment by lonvia** [comment] 2019-05-07 21:07
I've run into a similar error recently and wonder if the issue here is that a python module (in this case: ogr) is missing and php is giving us the wrong error message.

**Comment by Emil-Zhou** [comment] 2019-05-08 09:38
Thanks for your information.
Nominatim better and better.

By the way, could you please location the source code of process the data from the original TIGER data to create the SQL.

**Comment by Emil-Zhou** [comment] 2019-05-08 09:39
I'm working on v3.2.0.
Thanks,

**Comment by mtmail** [comment] 2019-05-08 09:56
@Emil-Zhou The script that converts the TIGER data to *.sql files is `tiger_address_convert.py` in https://github.com/openstreetmap/Nominatim/tree/master/data-sources/us-tiger

**Comment by Emil-Zhou** [comment] 2019-05-08 10:14
@mtmail  Thanks,

**Comment by Emil-Zhou** [comment] 2019-05-09 06:21
Thanks Guys

**Comment by lonvia** [comment] 2019-05-09 07:28
I'd like to figure out if we can improve the error message here. Reopening for that.

**Comment by Emil-Zhou** [comment] 2019-05-10 03:25
I see, Thanks.

**Comment by lonvia** [comment] 2019-06-10 21:41
So it wasn't the module. The only way to reproduce the error is to have a missing python binary. Closing now as 'can't reproduce'.

**Closed by lonvia** 2019-06-10 21:41 UTC
