### ISSUE TITLE
Can not resolve streetnames, Buffer is not owned by Portal

### ISSUE THREAD

**Issue by hackenjoe** [openstreetmap/Nominatim#1335] opened 2019-03-17 12:39 UTC
Hello,

I wanted to import europe.pbf and as I started the import script with the command:
`./utils/setup.php --osm-file europe-latest.osm.pbf --all --osm2pgsql-cache 14000 2>&1 | tee setup.log`

the import process stopped at rank 30 with following error statement:
`Error: "nominatim UPDATE failed: ERROR:  buffer 179261 is not owned by resource owner Portal"`

Furthermore, I can not resolve streetnames with housenumber. Doing so, it will return following error message:

> Message: Database request failed
SQL Error: DB Error: unknown error
Details:
SELECT place_id FROM placex WHERE parent_place_id in (110165299,110165253,110165247,108380397,106276643,104222827,101639227,101639390,101638986,99539118,98785744,93680061,92310133,91015646,90856499,66841982,66277011,60226430,60161117,59825189)  AND transliteration(housenumber) ~* E'\\m22\\M' [nativecode=ERROR:  canceling statement due to statement timeout

But geocoding for cities, countries and states is working just not for street names.

Error log in postgresql returns the same error:
> 2019-03-17 13:32:27.437 CET [11265] www-data@Europe ERROR:  canceling statement due to statement timeout
2019-03-17 13:32:27.437 CET [11265] www-data@Europe STATEMENT:  SELECT place_id FROM placex WHERE parent_place_id in (110165299,110165253,110165247,108380397,106276643,104222827,101639227,101639390,101638986,99539118,98785744,93680061,92310133,91015646,90856499,66841982,66277011,60226430,60161117,59825189)  AND transliteration(housenumber) ~* E'\\m22\\M'

Hardware Details: 4 Intel CPU, 32 GB Ram

How can we fix this issue? Or what's the problem here?

**Comment by mtmail** [comment] 2019-03-17 21:57
User reported the 'is not owned by' before but it's something database internal Nominatim doesn't control. Users then reported either rebooting the server, different hardware or just trying the import again worked. https://github.com/openstreetmap/Nominatim/issues/1168

With crash in rank 30 you're in luck and the import can continue exactly where it took off, even after a reboot. See first entry in https://nominatim.org/release-docs/develop/admin/Faq/ (that's the master branch of the install documentation, not linked from nominatim.org directly so you couldn't have seen the page).

Searches don't work yet until the import finished. The timeout you see is likely a missing database index. Those are created later in the setup.

**Comment by hackenjoe** [comment] 2019-03-18 17:59
It is again on rank 30 but not stopping so far. But now I can not even search for states or cities which was possible where nominatim was indexing on rank 26. Now I get for every search query the statement timeout with "unknown error".

>Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.
Message: Could not get places for search terms.
SQL Error: DB Error: unknown error
Details:
SELECT place_id,0::int as exactmatch FROM search_name WHERE name_vector @> ARRAY[21595881] ORDER BY (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75001-(search_rank::float/40) ELSE importance END) DESC LIMIT 20 [nativecode=ERROR:  canceling statement due to statement timeout]

What I can see in comparison with the first search exception is that Nominatim has now added beside `place_id, 0::int as exactmatch...`

I just guess it's normal until rank 30 has been finished? But why I could search for coarser locations at previous ranks?

**Comment by lonvia** [comment] 2019-03-18 20:35
You must not run queries before the import is completely finished. It does not work. It's like trying to drive away in a car before its wheels are assembled.

Closing as a duplicate of #1168.

**Closed by lonvia** 2019-03-18 20:35 UTC
