### ISSUE TITLE
Reverse geocoding rewrite

### ISSUE THREAD

**Issue by RemiBou** [openstreetmap/Nominatim#512] opened 2016-08-31 09:49 UTC
Hi,

I don't understand the reverse geocoding sql :

`select place_id,parent_place_id,rank_search,calculated_country_code 
FROM placex WHERE ST_DWithin(ST_SetSRID(ST_Point(2.1833,41.38334),4326), geometry, 0.0008) 
and rank_search != 28 
and rank_search >= 30 
and (name is not null or housenumber is not null) 
and class not in ('waterway','railway','tunnel','bridge','man_made') 
and indexed_status = 0 
and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(2.1833,41.38334),4326), centroid, 0.0008)) 
ORDER BY ST_distance(ST_SetSRID(ST_Point(2.1833,41.38334),4326), geometry) ASC limit 1`

Basicly it checks that :
- 1- the GPS point is in the geometry (I guess its the polygon, the point of the node, or the road)
- 2- if it's not a polygon, also check that it's near the centroid 

2 issues for me :
- let say my point is in a city and but a place with a lower search_rank (a shop for instance) is defined in placex but is not in this city : this shop will be used and on the results we'll have the wrong city.
- why are we checking #2, isn't #1 sufficient ? If not why are we checking #1 with non polygon geometry ?

**Comment by mtmail** [comment] 2016-09-01 10:47
Given a search point (`2.1833,41.38334` in your example) Nominatim will look for a feature in a very small radius (10 centremeters, not sure), then expand the radius until it finds something. So it's possible the result will be 100m or even 20km away from the search point. 20km happens in sparse populated areas. 100m is also annoying if the search point is in the center of a street and the nearest restaurant on a different street gets returned. What you describe with results from another city is also possible.

Regarding issue 1: yes, administrative areas are ignored. The result might even be in a another country. We can't rely on administrative areas being present, in many parts of the world those are missing.

Regarding issue 2: Similar to 1. In well mapped parts of the world each coordinate could be linked to an administrative area. Often though we have incomplete data where e.g. cities are just nodes. Nominatim was written 5 years ago when OpenStreetMap was much less mapped.

I hope this sheds some light on the algorithm and current drawbacks.

**Comment by RemiBou** [comment] 2016-09-02 14:21
mtmail, thanks for your answer. I think I'll change my nominatim instance code because I'm using it only for europe (and mostly western europe) and all the cities and administrative zone seems well mapped here.

**Comment by lonvia** [comment] 2016-09-27 22:04
To add to @mtmail's answer: the current algorithm for reverse is less than ideal and was indeed made for times when we had a lot fewer administrative polygons. Contributions to improve the algorithm would be very welcome. 

Here are some rough ideas I had:

First of all the zoom parameter is counter-intuitive. It only cuts the final result to the requested zoom which causes the strange results you observed. I'd change it to search directly only for features with the corresponding rank_search or lower. Or maybe add a new parameter to achieve that.

Then I'd change the reverse search to a two-step algorithm: first search for the closest road _or_ POI (i.e. anything with rank_search >= 26, unless street zoom is requested, in which case we'd only look for streets to start with). If the result is a street and zoom level requests POI level, find the closest object (up to a certain radius) of which the street is a parent.

If no results are found at that level, things get a bit more complicated:

 1. look for the place polygon with the highest rank_search that contains the requested location. 
 2. look for any place nodes with a higher rank_search than the polygon and a rank_search < min(26, requested rank_search).
 3. Choose the one with the highest rank_search and closest to the requested location.

I haven't tested any of that yet and there may be even better solutions to the problem. We'd certainly need to collect a few good test cases before changing all that.

**Comment by RemiBou** [comment] 2016-10-05 07:25
Why would you search for roads before polygon ? If polygons are in the db it's a more precise data than the roads (especially for gps point which are far away from any poi or road)

Look for the place polygon with the lowest rank_search that contains the requested location.
if no polygon
search for the closest road or POI
else
search for the closest road or POI within the polygon

**Comment by lonvia** [comment] 2016-10-05 21:13
It is important to keep in mind that the reverse endpoint in Nominatim doesn't compute the address for the location given. It simply returns the OSM object that best describes the location given. That's a rather clever optimization because it means we don't have to do complicated geometry queries over the data but we can simply fetch one object and return it together with it's precomputed address.

For the most frequent reverse geocoding case, namely where somebody wants to know which street they are currently on, we can get away with a single query when starting with searching for the nearest road.

The other reason is that it is much cheaper to find the closest object than to compute if a location is contained in an area. In fact, performance used to be so much of a problem that the current implementation goes some lengths to avoid it. Postgis has improved in the meantime, so I would not completely avoid a contains check but it's still a good idea to minimize use.

**Comment by Megachip** [comment] 2017-10-10 08:25
Another unclear/wrong location:

https://nominatim.openstreetmap.org/details.php?place_id=145064937
Why collis is returned here? its far far away...

**Comment by mtmail** [comment] 2017-10-10 09:30
@Megachip You're commenting on an issue that got closed 6 months ago, with the last comment 12 months ago. You can create a new issue with your observation, but we won't reopen the closed issue.

**Comment by Megachip** [comment] 2017-10-10 20:04
@mtmail Thx for the information. But creating new issues will result in clothing them as duplicate of that (as you see above). Also this issue here is open. So I'm not sure how to report these issues.

**Comment by lonvia** [comment] 2017-10-10 20:40
@Megachip This issue is indeed still open but it has nothing at all to do with what you are reporting. Address computation of OSM objects (which is your issue) and looking up objects for the reverse endpoint (which is this issue) touch completely different parts of the software. That said, your issue with well known and documented, e.g. see issues 236 and 575.

**Comment by Megachip** [comment] 2017-10-11 17:53
@lonvia Ok. But I'm still confused, cause you merged #799 as duplicate into this ticket and now it's completely different. So as @mtmail said, I will create a new ticket. 

But for all, It seems there are not much chances for short times fixes of these bugs. But hopefully it helps to document them nevertheless...

**Comment by lonvia** [comment] 2018-07-04 18:10
Implemented with #1054.

**Closed by lonvia** 2018-07-04 18:10 UTC
Labels: Reverse, enhancement
