### ISSUE TITLE
a street between 2 boundary

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/Nominatim#897] opened 2018-01-29 18:26 UTC
a street is on the edge of two municipalities, each with its own postal code.
When you ask for an address (node or way) on one side, the result is wrong.
the localisation in the boundary of the municipality and the postal code are ignored to the benefit of the street which does not mean anything since it is straddling the 2.
Buildings in each municipality are grouped into one associatedStreet per side of the street with the correct addr:city and addr:postcode, but Nominatim does not seem to use them.
the request for a node : https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=2528505484
the request for a way : https://nominatim.openstreetmap.org/reverse?osm_type=W&osm_id=245705266
both wrongly return 1081 Koekelberg in stead of 1080 Molenbeek
the requested node https://www.openstreetmap.org/node/2528505484
the requested way https://www.openstreetmap.org/way/245705266
postal_code boundary https://www.openstreetmap.org/relation/3379417
municipality boundary https://www.openstreetmap.org/relation/58255
the way used for the boundary https://www.openstreetmap.org/way/28825406
associatedStreet for on side https://www.openstreetmap.org/relation/3321170

how to solve this problem?
Would a merge of road nodes with boundary nodes allow to manage this situation "road between 2 municipalities" ?
should Nominatim use tags from the associateStreet before trying to guess the values according to the road ? it seems to me to be the best solution since it would use the most accurate information available.

NB: I have the same issue when the boundary cross the street
https://www.openstreetmap.org/way/240661380 is in "1081 Koekelberg" but Nominatim wrongly return 1080 Molenbeek"
if you prefer, I can make another issue for this case or put this in #328

**Comment by lonvia** [comment] 2018-01-29 19:31
Duplicate of #328.

There is nothing you can do about it mapping-wise at the moment. Just put the situation in as it is (which looks correct now). Nominatim just can't handle it until somebody implements support for it. I can't tell when that will be.

**Closed by lonvia** 2018-01-29 19:31 UTC
Labels: Indexing, duplicate
