### ISSUE TITLE
Error executing ./utils/specialphrases.php

### ISSUE THREAD

**Issue by khamooshi** [openstreetmap/Nominatim#749] opened 2017-06-09 08:45 UTC
When I execute this line:
./utils/specialphrases.php --wiki-import > specialphrases.sql

I get the following error:
PHP Fatal error: Class 'Transliterator' not found in /path/Nominatim/build/utils/specialphrases.php on line 22

It used to work few days ago!

**Comment by khamooshi** [comment] 2017-06-09 09:15
Scripts in docs/ folder needs to be updated with php-intl

**Comment by lonvia** [comment] 2017-06-09 09:41
Duplicate of #747.

**Closed by lonvia** 2017-06-09 09:41 UTC
