### ISSUE TITLE
to find wrong address

### ISSUE THREAD

**Issue by Laniuscollurio** [openstreetmap/Nominatim#881] opened 2018-01-10 13:05 UTC
Hi, I'm going to look for the address "7, Via Campi Magnano" [http://nominatim.openstreetmap.org/search.php?q=7+campi+magnano&polygon_geojson=1&viewbox=](url) but nominatim finds a wrong address "7, Cascina Carrera, Magnano" [http://nominatim.openstreetmap.org/details.php?place_id=62443841](url). All data in OSM seems all rights.  There is the same error for others address of "Via Campi", I think because in "Via Campi" details [ http://nominatim.openstreetmap.org/details.php?place_id=79088343
](url) in "House" there are a lot of nodes both the toponym
Marco

**Comment by mtmail** [comment] 2018-01-10 13:52
Just rephrasing:

For query `7, Via Campi, Magnano` http://nominatim.openstreetmap.org/search.php?q=7+via+campi,+magnano&format=html the first and only result is in a nearby village. That house is attached to a place (villiage) and next to an unnamed road.

http://www.openstreetmap.org/node/4818374951
`<tag k="addr:city" v="Magnano"/><tag k="addr:housenumber" v="7"/><tag k="addr:place" v="Cascina Carrera"/><tag k="addr:postcode" v="13887"/>`

We expect the result to be in the city

http://www.openstreetmap.org/node/4818374646
`<tag k="addr:city" v="Magnano"/><tag k="addr:housenumber" v="7"/><tag k="addr:postcode" v="13887"/><tag k="addr:street" v="Via Campi"/>`

**Comment by lonvia** [comment] 2018-01-10 22:01
It is a bit hard to see but the problem here is that [Cascina Carrera](http://www.openstreetmap.org/node/4803286528) is wrongly tagged place=farm instead of place=hamlet or place=village.

The addresses in Cascina Carrera are all correctly tagged with `addr:place=Cascina Carrera`. Problem is that Nominatim needs an actual place with multiple houses to exists to take that tag into account. `place=farm` or `place=locality` are not enough. `place=isolated_dwelling`, `place=suburb`, `place=hamlet` etc. all work fine. In absence of such a place, Nominatim assigns a standard street address using the closest named street, which in this case is actually quite far away.

I've now retagged Cascina Carrera as hamlet and all is well. You should check the settlements in the area. There might be others with the same problem.

**Comment by musuruan** [comment] 2018-01-11 07:34
I see some issues with this algorithm. 

First, a correctly mapped address is not found due to problems elsewhere.

Moreover, it is wrong, at least in Italy, to exclude place=farm from address searches and to link addresses to houses. Addresses can be anywhere, not just on houses. According to Italian Law **"Address numbering is constituted by the numbers that distinguish the external accesses, i.e. those that from the circulation area (street, squares, etc) enter, directly or indirectly, to the houses, shops, offices, garages, etc...".** Therefore farms can have addresses too.

We also have many addr:place where there is no corresponding place tag because there currently isn't a valid value that describe them (mostly "dispersed settlements"). So these addresses will not be found. Here there some examples in Netro: https://drive.google.com/file/d/0B65acVCG5NRQTVZ1MFg0aF9jSDQ/view?usp=sharing

Lastly, again in Italy, the postal address for a place may include the kind of settlement (i.e. Frazione, Casale, etc). But usually this is omitted in the place name (e.g. https://www.openstreetmap.org/node/5236332829). These address will never be found too.

**Comment by lonvia** [comment] 2018-01-11 08:30
First of all, there is a common confusion between geographic descriptions and postal addresses. Nominatim does the former, i.e. it tells you the administrative units a place is in. And search works the same way. It would be nice if places could also be found by their postal address when that differs significantly from the geographic location but that is still on the TODO list, see #148.

 `addr:place` was explicitly invented to tie house numbers to existing settlements. I would consider in particular your last example as a misuse of the tag. Use `addr:full` if the place has a postal address that has nothing to do with (mapped) geographic features around.

There might be a case to interpret place=farm as a administrative unit that can be part of an address. However that requires @213 to limit the change to Italy and I'd also like to see evidence that there is an agreed upon tagging schema in Italy (i.e. documented in the wiki). There is no consistent use whatsoever at the moment. It is used for everything: uninhabited places, single houses, suburbs, villages, etc. So 'fixing' the case above would wreck havoc to lots of other searches.

Closing as duplicate of #148. If you like `place=farm` to be considered as part of addresses in Italy open a new ticket after having discussed and agreed on that in the Italian community.

**Closed by lonvia** 2018-01-11 08:30 UTC
