### ISSUE TITLE
Nominatim does not find partial string match

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/Nominatim#1232] opened 2018-11-08 21:23 UTC
When searching for “[groupe médical du plateau](https://nominatim.openstreetmap.org/search.php?q=groupe+m%C3%A9dical+du+plateau&polygon_geojson=1&viewbox=)” than Nominatim does not find any result.

However, when searching for “[polyclinique groupe médical du plateau](https://nominatim.openstreetmap.org/search.php?q=polyclinique+groupe+m%C3%A9dical+du+plateau&polygon_geojson=1&viewbox=)” it does find [the corresponding OSM element](https://www.openstreetmap.org/node/4437963790) who’s name value is “Polyclinique Groupe Médical du Plateau”

I would expect that also the first, shorter search term would also find the same OSM element.

**Comment by lonvia** [comment] 2018-11-16 20:18
Duplicate of #94.

**Closed by lonvia** 2018-11-16 20:18 UTC
