### ISSUE TITLE
Dutch postcodes containing a space are not found

### ISSUE THREAD

**Issue by PanderMusubi** [openstreetmap/Nominatim#1027] opened 2018-04-30 07:52 UTC
Dutch postcodes containing a space are not found. This bug came to light by using Thunderbird Address Book which can open Nominatim for an address.

Examples that do work are:
* [Neude without space](https://nominatim.openstreetmap.org/search.php?q=Neude+11%2C%2CUtrecht%2C%2C3512AE%2C&polygon_geojson=1&viewbox=) and [Neude with space](https://nominatim.openstreetmap.org/search.php?q=Neude+11%2C%2CUtrecht%2C%2C3512+AE%2C&polygon_geojson=1&viewbox=)
* [Stadsplateau without space](https://nominatim.openstreetmap.org/search.php?q=Stadsplateau+1%2C%2CUtrecht%2C%2C3521AZ%2C&polygon_geojson=1&viewbox=) and [Stadsplateau with space](https://nominatim.openstreetmap.org/search.php?q=Stadsplateau+1%2C%2CUtrecht%2C%2C3521+AZ%2C&polygon_geojson=1&viewbox=)

Examples that do not work with space are:
* [Helling without space (working)](https://nominatim.openstreetmap.org/search.php?q=Helling%2014%2C%2CUtrecht%2C%2C3523%20CC%2C&polygon_geojson=1&viewbox=) and [Helling with space (not working)](https://nominatim.openstreetmap.org/search.php?q=Helling%2014%2C%2CUtrecht%2C%2C3523%20CC%2C&polygon_geojson=1&viewbox=)
* [Meerveldstraat without space (working)](https://nominatim.openstreetmap.org/search.php?q=Meerveldstraat+3%2C%2CAlmere%2C%2C1359HH%2C&polygon_geojson=1&viewbox=) and [Meerveldstraat with space (not working)](https://nominatim.openstreetmap.org/search.php?q=Meerveldstraat+3%2C%2CAlmere%2C%2C1359+HH%2C&polygon_geojson=1&viewbox=)

Example that doesn't work with or without space is:
* [Europalaan 34 (een bouwmarkt)](https://nominatim.openstreetmap.org/search.php?q=Europalaan+34%2C%2CUtrecht%2C%2C3525KS%2C&polygon_geojson=1&viewbox=)

It doesn't matter is the space in the url is a space ` `, a plus `+` or `%20`.

**Comment by PanderMusubi** [comment] 2018-04-30 16:44
Note that Thunderbird Address Book creates search links in this way. Perhaps it should use more advanced search with named fields?

**Comment by PanderMusubi** [comment] 2018-05-01 15:19
Note that Thunderbird Address Book creates search links in this way. Perhaps it should use more advanced search with named fields?

**Comment by mtmail** [comment] 2018-05-01 15:31
Base issue is that Nominatim currently can't handle 4 digit Dutch postcodes, it simply doesn't know where they are. It's been reported in https://github.com/openstreetmap/Nominatim/issues/1009 and we want to fix it with https://github.com/openstreetmap/Nominatim/issues/1011

**Comment by PanderMusubi** [comment] 2018-05-01 16:07
I'm referring to postcodes that do have the two letters, such as `1234 AB`. Only the space that is in there is not being processed properly. Removing the space is one way of solving it, however many people use the space. Think that is also still the official format.

**Comment by PanderMusubi** [comment] 2018-05-01 16:11
@mtmail So if it is know which value is which type, do you advise using named parameters? The Thuderbird Address Book known which part is the street name, postal code, city, etc.

**Comment by PanderMusubi** [comment] 2018-05-01 18:37
Haha.

If not for a workaround and independent of the issue, would you recommend Thunderbird (and others) using a structured query?

**Comment by mtmail** [comment] 2018-05-02 11:39
Structured queries are still marked experimental in our documentation https://wiki.openstreetmap.org/wiki/Nominatim#Search I'd use unstructured, basically list address components comma separated sorted by small->large (house number -> country).

There's quite a few places in the world with are both cities and states (Berlin, Hamburg) or city and county (most metropolitan areas like London). Manhatten (a borough) or Paris Arrondissements (a quarter) don't seem to into either a suburb or city definition.

**Comment by lonvia** [comment] 2018-05-05 21:25
Duplicate of #927.

**Closed by lonvia** 2018-05-05 21:25 UTC
