### ISSUE TITLE
Add places on Open Street Map 

### ISSUE THREAD

**Issue by gnosis7bit** [openstreetmap/Nominatim#1059] opened 2018-06-12 14:07 UTC
I installed the [Nominatim](https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-16/) on an EC2 instance in AWS and importing the whole world.

For me its use is similar to Facebook and Instagram in relation to the location of the posts. In my app a post has a location, so users can filter posts from a specific location.

So far so good, now I need to let the user create places according to their need and that place appears in the Search and Reverse API of Nominatim.

I need a simple interface, like [Facebook's.](https://www.facebook.com/help/iphone-app/175921872462772)

If it does not have anything like that, can you point out a way for me to develop the solution myself? I've already researched several OSM editors and found nothing like it.

Thank you

**Comment by mtmail** [comment] 2018-06-12 14:10
Duplicate of https://help.openstreetmap.org/questions/64175/add-places-on-open-street-map

**Closed by mtmail** 2018-06-12 14:10 UTC

**Comment by gnosis7bit** [comment] 2018-06-12 14:16
I created this question on the forum right now.
@mtmail you could leave it open, please? I need to find the solution as soon as possible.
Thankful
