### ISSUE TITLE
Comma throws off search result

### ISSUE THREAD

**Issue by b-jazz** [openstreetmap/Nominatim#1325] opened 2019-03-06 20:07 UTC
As noticed in this tweet this morning: https://twitter.com/TransitNinja205/status/1103301248969781248

Searching for the full name of this school:

https://www.openstreetmap.org/search?query=High%20School%20for%20Construction%20Trade%2C%20Engineering%20and%20Architechture#map=19/40.68927/-73.84117

Returns no results, but remove the comma and the school relation is correctly returned:

https://www.openstreetmap.org/search?query=High%20School%20for%20Construction%20Trade%20Engineering%20and%20Architechture#map=19/40.68927/-73.84117

**Comment by lonvia** [comment] 2019-03-06 20:11
Duplicate of #698. This is not fixable without fundamentally changing how Nominatim works.

**Closed by lonvia** 2019-03-06 20:11 UTC
