### ISSUE TITLE
Adress found only when comma is set after postal code?

### ISSUE THREAD

**Issue by mikesch1** [openstreetmap/Nominatim#1132] opened 2018-08-09 10:32 UTC
Hi,
have following problem.

I have created 2 new Adresses in a certain street. The building has two entrances with two different house numbers. 

1. Nordstraße 5, 27476 Cuxhaven
(If searching for this adress in openstreet it is found)
2. Nordstraße 3, 27476 Cuxhaven
(if searching for this adress it is not found)
As soon as I put a comma behind the postal code - the adress is found?
E. g. Nordstraße 3, 27476, Cuxhaven or Nordstraße 3 27476, Cuxhaven

The adress is set up as a building in the "Nordstraße" - marked with 2 Adress Points (No 3 and No 5 )
I have tried meanwhile several versions, even seperating the one building into 2 buildings etc.
The adress with the No. 3 is always only found when putting in the "comma" after the postal code?

Can you help?

regards
Michael

**Comment by Alex2782** [comment] 2018-08-13 19:27
Hi Michael,

Nr. 1 "Nordstraße 5, 27476 Cuxhaven", now works? i can't reproduce it

https://nominatim.openstreetmap.org/search.php?q=Nordstra%C3%9Fe+5%2C+27476+Cuxhaven&polygon_geojson=1&viewbox=


regards
Alex

**Comment by lonvia** [comment] 2018-08-13 19:44
@Alex2782 "Nordstr. 3" is the critical search, not "Nordstr 5".

It's a complicated place. The database has both "Nordstr. 3" and "27476 Cuxhaven" as full search terms (i.e. somebody has tagged something with name=27476 Cuxhaven). This throws Nominatim off when trying to decompose the search query. It essentially gives up before reaching the right interpretation where 3 is a housenumber and 27476 a postcode. This certainly is a bug but unfortunately very hard to fix without breaking something else.

**Comment by Alex2782** [comment] 2018-08-13 22:52
ok thanks, I will try to understand this bug first

**structured request** works, maybe "libpostal" can help
street=Nordstraße 3
city=Cuxhaven
postalcode=27476

https://nominatim.openstreetmap.org/search.php?&street=Nordstra%C3%9Fe+3&city=Cuxhaven&postalcode=27476

**Comment by Alex2782** [comment] 2018-08-14 08:58
> how could it be reported to someone 

You done this already here, but Nominatim is a OpenSource-Project.
there's no guarantee that it will fix it right for everyone.


lonvia wrote
> This certainly is a bug but unfortunately very hard to fix without breaking something else.

**Comment by lonvia** [comment] 2018-11-16 23:53
Fixed in 85f32d6c0f47a73bb173a0b2f59b65da734c586c.

**Closed by lonvia** 2018-11-16 23:53 UTC
