### ISSUE TITLE
Nominatim geocoding slow queries optimization

### ISSUE THREAD

**Issue by aaphadke** [openstreetmap/Nominatim#578] opened 2016-11-15 07:54 UTC
Hi ,

We are using Nominatim with following configs for geocoding (getting lat and lon)
Nominatim Version 2.4.0
16 core CPUS,     122GB RAM    320GB SSD HD

And our postgresql.conf looks like following

shared_buffers = 1GB            # min 128kB
maintenance_work_mem = 10GB        # min 1MB
work_mem = 50MB                # min 64kB
maintenance_work_mem = 10GB        # min 1MB
effective_cache_size = 24GB
synchronous_commit = off        # synchronization level;
checkpoint_segments = 100        # in logfile segments, min 1, 16MB each
checkpoint_timeout = 10min        # range 30s-1h
checkpoint_completion_target = 0.9    # checkpoint target duration, 0.0 - 1.0

We are seeing following queries taking time (almost always> 5 seconds) in postgres logs for geocode
http://nominatim.local.com/nominatim/search.php?format=json&limit=1&q=322+West+Street%2CCarlisle%2CMassachusetts%2C01741%2CUnited+States

LOG:  duration: 19915.484 ms  statement: select place_id, (select count(*) from (select unnest(ARRAY[4523464,5730972,36867388]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[2832006] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[15678054,348921,362979,36867389] and country_code = 'us' order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2

http://nominatim.local.com/nominatim/search.php?format=json&limit=1&q=106+Winchester+Street+%232%2CBrookline%2CMassachusetts%2C02446%2CUnited+States

LOG:  duration: 13518.676 ms  statement: select place_id, (select count(*) from (select unnest(ARRAY[6122619,5730972,18878827]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[2294177] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[1997025,53652,362979,18878828] and country_code = 'us' order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2

Can someone suggest what are we missing here? Anyways to improve like creating indexes or changing postgres configs?

Thanks.

**Comment by lonvia** [comment] 2016-11-15 08:02
As a simple meassure try running `psql -d nominatim -c ANALYZE`. Does that help?

**Comment by aaphadke** [comment] 2016-11-16 07:42
It did not help that much after running ANALYZE on nominatim db.Still seeing following in the logs for long queries. Any other suggestions? Do you think if there is anything wrong with the import?

LOG:  duration: **22019.747 ms**  statement: select place_id, (select count(*) from (select unnest(ARRAY[8053860,18280874,1813026,11573732]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1038416] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[12924,13740561,29688,57845,19924055] and address_rank between 16 and 27 order by exists(select place_id from placex where parent_place_id = search_name.place_id and transliteration(housenumber) ~* E'\\m1988 1\\M' limit 1) desc, - abs(26 - address_rank) + 3 DESC, exactmatch DESC limit 20

LOG:  duration: **7886.240 ms**  statement: select place_id, (select count(*) from (select unnest(ARRAY[8053860,2857736,103133,18280874,1813026,11573732]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1038416] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[12924,41791,103133,13740561,29688,57845,19924055] order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2

LOG:  duration: **154431.201 ms**  statement: select place_id, (select count(*) from (select unnest(ARRAY[7003575]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[22841] and nameaddress_vector @> ARRAY[51882,19924055] order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2

**Comment by lonvia** [comment] 2016-11-16 09:11
Yes, there is definitely something wrong. On your hardware the queries should finish in a couple of milliseconds. Can you please provide the output of the following commands run from the postgres console (`psql nominatim`):

 * \d search_name
 * \d placex
 * EXPLAIN  select place_id, (select count() from (select unnest(ARRAY[8053860,18280874,1813026,11573732]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1038416] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[12924,13740561,29688,57845,19924055] and address_rank between 16 and 27 order by exists(select place_id from placex where parent_place_id = search_name.place_id and transliteration(housenumber) ~ E'\m1988 1\M' limit 1) desc, - abs(26 - address_rank) + 3 DESC, exactmatch DESC limit 20;
 * SELECT * FROM word WHERE word_id IN (8053860,18280874,1813026,11573732, 1038416, 12924,13740561,29688,57845,19924055);

**Comment by aaphadke** [comment] 2016-11-16 18:47
Thanks Ionvia for answers so far ..appreciate your help!

Below are the outputs of the commands you asked

**nominatim=# \d search_name**
                Table "public.search_name"
       Column       |          Type           | Modifiers
--------------------+-------------------------+-----------
 place_id           | bigint                  |
 search_rank        | integer                 |
 address_rank       | integer                 |
 importance         | double precision        |
 country_code       | character varying(2)    |
 name_vector        | integer[]               |
 nameaddress_vector | integer[]               |
 centroid           | geometry(Geometry,4326) |
Indexes:
    "idx_search_name_centroid" gist (centroid)
    "idx_search_name_name_vector" gin (name_vector) WITH (fastupdate=off)
    "idx_search_name_nameaddress_vector" gin (nameaddress_vector) WITH (fastupdate=off)
    "idx_search_name_place_id" btree (place_id)

**nominatim=# \d placex**
                       Table "public.placex"
         Column          |            Type             | Modifiers
-------------------------+-----------------------------+-----------
 place_id                | bigint                      | not null
 partition               | integer                     |
 osm_type                | character(1)                | not null
 osm_id                  | bigint                      | not null
 class                   | text                        | not null
 type                    | text                        | not null
 name                    | hstore                      |
 admin_level             | integer                     |
 housenumber             | text                        |
 street                  | text                        |
 addr_place              | text                        |
 isin                    | text                        |
 postcode                | text                        |
 country_code            | character varying(2)        |
 extratags               | hstore                      |
 geometry                | geometry(Geometry,4326)     | not null
 parent_place_id         | bigint                      |
 linked_place_id         | bigint                      |
 rank_address            | integer                     |
 rank_search             | integer                     |
 importance              | double precision            |
 indexed_status          | integer                     |
 indexed_date            | timestamp without time zone |
 wikipedia               | text                        |
 geometry_sector         | integer                     |
 calculated_country_code | character varying(2)        |
 centroid                | geometry(Geometry,4326)     |
Indexes:
    "idx_place_id" UNIQUE, btree (place_id)
    "idx_placex_adminname" btree (make_standard_name(name -> 'name'::text), rank_search) WHERE osm_type = 'N'::bpchar AND rank_search < 26
    "idx_placex_geometry" gist (geometry)
    "idx_placex_linked_place_id" btree (linked_place_id)
    "idx_placex_osmid" btree (osm_type, osm_id)
    "idx_placex_parent_place_id" btree (parent_place_id) WHERE parent_place_id IS NOT NULL
    "idx_placex_pendingsector" btree (rank_search, geometry_sector) WHERE indexed_status > 0
    "idx_placex_rank_address" btree (rank_address)
    "idx_placex_rank_search" btree (rank_search)
    "idx_placex_reverse_geometry" gist (geometry) WHERE rank_search <> 28 AND (name IS NOT NULL OR housenumber IS NOT NULL) AND (class <> ALL (ARRAY['waterway'::text, 'railway'::text, 'tunnel'::text, 'bridge'::text]))
    "idx_placex_sector" btree (geometry_sector, rank_address, osm_type, osm_id)
Triggers:
    placex_before_delete AFTER DELETE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_delete()
    placex_before_insert BEFORE INSERT ON placex FOR EACH ROW EXECUTE PROCEDURE placex_insert()
    placex_before_update BEFORE UPDATE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_update()

**nominatim=# EXPLAIN** select place_id, (select count(*) from (select unnest(ARRAY[8053860,18280874,1813026,11573732]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1038416] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[12924,13740561,29688,57845,19924055] and address_rank between 16 and 27 order by exists(select place_id from placex where parent_place_id = search_name.place_id and transliteration(housenumber) ~ E'\m1988 1\M' limit 1) desc, - abs(26 - address_rank) + 3 DESC, exactmatch DESC limit 20;
                                                                                    QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=136946.74..136946.75 rows=1 width=419)
   ->  Sort  (cost=136946.74..136946.75 rows=1 width=419)
         Sort Key: ((SubPlan 2)), (((- abs((26 - search_name.address_rank))) + 3)), ((SubPlan 1))
         ->  Bitmap Heap Scan on search_name  (cost=392.56..136946.73 rows=1 width=419)
               Recheck Cond: (name_vector @> '{1038416}'::integer[])
               Filter: ((address_rank >= 16) AND (address_rank <= 27) AND (array_cat(nameaddress_vector, '{}'::integer[]) @> '{12924,13740561,29688,57845,19924055}'::integer[]))
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00..392.56 rows=34742 width=0)
                     Index Cond: (name_vector @> '{1038416}'::integer[])
               SubPlan 1
                 ->  Aggregate  (cost=3.53..3.54 rows=1 width=0)
                       ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0)
                             ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=0)
                                   ->  Append  (cost=0.00..3.01 rows=200 width=0)
                                         ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=0)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0)
                                         ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=0)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0)
               SubPlan 2
                 ->  Limit  (cost=61.02..8182.89 rows=1 width=8)
                       ->  Bitmap Heap Scan on placex  (cost=61.02..8182.89 rows=1 width=8)
                             Recheck Cond: (parent_place_id = search_name.place_id)
                             Filter: (transliteration(housenumber) ~ 'm1988 1M'::text)
                             ->  Bitmap Index Scan on idx_placex_parent_place_id  (cost=0.00..61.02 rows=2045 width=0)
                                   Index Cond: (parent_place_id = search_name.place_id)
(24 rows)

**nominatim=# SELECT * FROM word WHERE word_id IN (8053860,18280874,1813026,11573732, 1038416, 12924,13740561,29688,57845,19924055);**
 word_id  |   word_token    |      word      | class | type | country_code | search_name_count | operator
----------+-----------------+----------------+-------+------+--------------+-------------------+----------
    12924 | 02              |                |       |      |              |              3397 |
    29688 | krakow          |                |       |      |              |               168 |
    57845 | poland          |                |       |      |              |               357 |
  1038416 |  2              | La Druga       |       |      |              |                 0 |
  1813026 |  krakow         | Krąków         |       |      |              |                 0 |
  8053860 |  02             | 02             |       |      |              |                 0 |
 11573732 |  poland         | Poeland        |       |      |              |                 0 |
 13740561 | szprotawa       |                |       |      |              |                 0 |
 18280874 |  szprotawa      | Szprotawa      |       |      |              |                 0 |
 19924055 |  united kingdom | United Kingdom |       |      |              |                 0 |
(10 rows)

**Comment by mtmail** [comment] 2016-11-16 22:47
On one of my servers I see similar cost for `Bitmap Heap Scan on placex`, a third of the cost on `Bitmap Heap Scan on search_name`, 4x less rows in `Bitmap Index Scan on idx_search_name_name_vector` (rows=7348)

For the `SELECT * FROM word WHERE word_id IN ` I get the same `search_name_count` counts for those tokens.

Same indices on `search_name` table. I don't have a `idx_placex_sector` index on the `placex` table.

Do you see the slowness for any country or just the US addresses? I've had an index missing on the `location_property_tiger` table once (only used for US addresses) and that was a huge performance hit for me.

**Comment by aaphadke** [comment] 2016-11-18 07:46
I see slowness in general for all the queries not just for US addresses.

Index on location_property_tiger looks like below. Is there anything missing here?

```
nominatim=# \d location_property_tiger
       Table "public.location_property_tiger"
     Column      |         Type         | Modifiers
-----------------+----------------------+-----------
 place_id        | bigint               |
 partition       | integer              |
 parent_place_id | bigint               |
 housenumber     | text                 |
 postcode        | text                 |
 centroid        | geometry(Point,4326) |
Indexes:
    "idx_location_property_tiger_housenumber_parent_place_id" btree (parent_place_id, housenumber)
    "idx_location_property_tiger_parent_place_id" btree (parent_place_id)
    "idx_location_property_tiger_place_id" btree (place_id)
Inherits: location_property
```

**Comment by lonvia** [comment] 2016-11-18 07:51
The outputs look all fairly normal, there is nothing obvious like a missing index. Do you mind running the query again but with `EXPLAIN ANALYSE` so we can see in which part of the query the time is actually lost?

**Comment by aaphadke** [comment] 2016-11-18 19:14
```
nominatim=# EXPLAIN ANALYZE select place_id, (select count(*) from (select unnest(ARRAY[8053860,18280874,1813026,11573732]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1038416] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[12924,13740561,29688,57845,19924055] and address_rank between 16 and 27 order by exists(select place_id from placex where parent_place_id = search_name.place_id and transliteration(housenumber) ~ E'\m1988 1\M' limit 1) desc, - abs(26 - address_rank) + 3 DESC, exactmatch DESC limit 20;
                                                                                    QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=136946.74..136946.75 rows=1 width=419) (actual time=50.762..50.762 rows=0 loops=1)
   ->  Sort  (cost=136946.74..136946.75 rows=1 width=419) (actual time=50.757..50.757 rows=0 loops=1)
         Sort Key: ((SubPlan 2)), (((- abs((26 - search_name.address_rank))) + 3)), ((SubPlan 1))
         Sort Method: quicksort  Memory: 25kB
         ->  Bitmap Heap Scan on search_name  (cost=392.56..136946.73 rows=1 width=419) (actual time=50.749..50.749 rows=0 loops=1)
               Recheck Cond: (name_vector @> '{1038416}'::integer[])
               Filter: ((address_rank >= 16) AND (address_rank <= 27) AND (array_cat(nameaddress_vector, '{}'::integer[]) @> '{12924,13740561,29688,57845,19924055}'::integer[]))
               Rows Removed by Filter: 31052
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00..392.56 rows=34742 width=0) (actual time=6.419..6.419 rows=31052 loops=1)
                     Index Cond: (name_vector @> '{1038416}'::integer[])
               SubPlan 1
                 ->  Aggregate  (cost=3.53..3.54 rows=1 width=0) (never executed)
                       ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0) (never executed)
                             ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=0) (never executed)
                                   ->  Append  (cost=0.00..3.01 rows=200 width=0) (never executed)
                                         ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=0) (never executed)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (never executed)
                                         ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=0) (never executed)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (never executed)
               SubPlan 2
                 ->  Limit  (cost=61.02..8182.89 rows=1 width=8) (never executed)
                       ->  Bitmap Heap Scan on placex  (cost=61.02..8182.89 rows=1 width=8) (never executed)
                             Recheck Cond: (parent_place_id = search_name.place_id)
                             Filter: (transliteration(housenumber) ~ 'm1988 1M'::text)
                             ->  Bitmap Index Scan on idx_placex_parent_place_id  (cost=0.00..61.02 rows=2045 width=0) (never executed)
                                   Index Cond: (parent_place_id = search_name.place_id)
 Total runtime: 50.841 ms
(27 rows)
```

**Comment by lonvia** [comment] 2016-11-18 19:20
So it looks like the query itself is not the problem if it went through in 50ms this time. Something else seems to be blocking on your system. That might be badly tuned SSDs, too many queries running in parallel or maybe some other process running in the background.

**Comment by aaphadke** [comment] 2016-11-20 22:55
@lonvia Looks like it got executed fast because of caching. If I flush cache I get following execution plans for some of the queries. Just curious to know how caching works here for queries?

```
nominatim=# EXPLAIN ANALYSE select place_id, (select count(*) from (select unnest(ARRAY[3812153,25341452]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[594748] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[9322262,60932,4043821] and country_code = 'de' order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2;

         QUERY PLAN

----------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------
----------------------------
 Limit  (cost=50754.94..50754.94 rows=1 width=427) (actual time=6685.477..6685.477 rows=0 loops=1)
   ->  Sort  (cost=50754.94..50754.94 rows=1 width=427) (actual time=6685.475..6685.475 rows=0 loops=1)
         Sort Key: (CASE WHEN ((search_name.importance = 0::double precision) OR (search_name.importance IS NULL)) THE
N (0.75::double precision - ((search_name.search_rank)::double precision / 40::double precision)) ELSE search_name.imp
ortance END), ((SubPlan 1))
         Sort Method: quicksort  Memory: 25kB
         ->  Bitmap Heap Scan on search_name  (cost=167.26..50754.93 rows=1 width=427) (actual time=6685.454..6685.454
 rows=0 loops=1)
               Recheck Cond: (name_vector @> '{594748}'::integer[])
               Filter: (((country_code)::text = 'de'::text) AND (array_cat(nameaddress_vector, '{}'::integer[]) @> '{9
322262,60932,4043821}'::integer[]))
               Rows Removed by Filter: 9140
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00..167.26 rows=13235 width=0) (actual ti
me=10.380..10.380 rows=9140 loops=1)
                     Index Cond: (name_vector @> '{594748}'::integer[])
               SubPlan 1
                 ->  Aggregate  (cost=3.53..3.54 rows=1 width=0) (never executed)
                       ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0) (never executed)
                             ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=0) (never executed)
                                   ->  Append  (cost=0.00..3.01 rows=200 width=0) (never executed)
                                         ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=0) (never
executed)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (never executed)
                                         ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=0) (never
executed)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (never executed)
 Total runtime: 6685.632 ms
(20 rows)

nominatim=# EXPLAIN ANALYSE select place_id, (select count(*) from (select unnest(ARRAY[33435980]) INTERSECT select unnest(nameaddress_vector))s) as exactmatch from search_name where name_vector @> ARRAY[1953226] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[29928] order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2;

               QUERY PLAN

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
----------------------------------------
 Limit  (cost=87595.27..87595.27 rows=2 width=427) (actual time=18771.173..18771.174 rows=2 loops=1)
   ->  Sort  (cost=87595.27..87595.56 rows=116 width=427) (actual time=18771.171..18771.172 rows=2 loops=1)
         Sort Key: (CASE WHEN ((search_name.importance = 0::double precision) OR (search_name.importance IS NULL
)) THEN (0.75::double precision - ((search_name.search_rank)::double precision / 40::double precision)) ELSE sea
rch_name.importance END), ((SubPlan 1))
         Sort Method: quicksort  Memory: 25kB
         ->  Bitmap Heap Scan on search_name  (cost=269.74..87594.11 rows=116 width=427) (actual time=10603.290.
.18771.159 rows=3 loops=1)
               Recheck Cond: (name_vector @> '{1953226}'::integer[])
               Filter: (array_cat(nameaddress_vector, '{}'::integer[]) @> '{29928}'::integer[])
               Rows Removed by Filter: 27112
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00..269.71 rows=23161 width=0) (act
ual time=23.775..23.775 rows=27115 loops=1)
                     Index Cond: (name_vector @> '{1953226}'::integer[])
               SubPlan 1
                 ->  Aggregate  (cost=3.53..3.54 rows=1 width=0) (actual time=0.111..0.111 rows=1 loops=3)
                       ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0) (actual time=0.107..0.107 rows=1
 loops=3)
                             ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=0) (actual time=0.105..0.105
 rows=1 loops=3)
                                   ->  Append  (cost=0.00..3.01 rows=200 width=0) (actual time=0.008..0.086 rows
=81 loops=3)
                                         ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=0) (
actual time=0.007..0.008 rows=1 loops=3)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (actual time=0.006
..0.007 rows=1 loops=3)
                                         ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=0) (
actual time=0.002..0.048 rows=80 loops=3)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (actual time=0.002
..0.021 rows=80 loops=3)
 **Total runtime: 18771.314 ms**
(20 rows)

```

**Comment by IsaacJT** [comment] 2016-11-22 09:25
Hello @lonvia and @aaphadke,

I am also seeing similar problems with Nominatim 2.5.1 and PostgreSQL 9.4, running on Debian 8 inside an LXC container, with the Europe dataset. The indices seem the same as @aaphadke  posted.

Queries are sometimes excruciatingly slow:

````
Limit  (cost=115737.61..115737.61 rows=1 width=455) (actual time=13320.253..13320.257 rows=14 loops=1)
   Buffers: shared hit=33 read=32675 dirtied=1710
   ->  Sort  (cost=115737.61..115737.61 rows=1 width=455) (actual time=13320.252..13320.253 rows=14 loops=1)
         Sort Key: ((SubPlan 2)), (((- abs((26 - search_name.address_rank))) + 3)), ((SubPlan 1))
         Sort Method: quicksort  Memory: 26kB
         Buffers: shared hit=33 read=32675 dirtied=1710
         ->  Bitmap Heap Scan on search_name  (cost=307.35..115737.60 rows=1 width=455) (actual time=1364.007..13320.216 rows=14 loops=1)
               Recheck Cond: (name_vector @> '{12924662}'::integer[])
               Filter: ((address_rank >= 16) AND (address_rank <= 27) AND ((country_code)::text = 'de'::text) AND (array_cat(nameaddress_vector, '{}'::integer[]) @> '{106011,20811464}'::integer[]))
               Rows Removed by Filter: 38236
               Heap Blocks: exact=32624
               Buffers: shared hit=33 read=32675 dirtied=1710
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00..307.35 rows=31380 width=0) (actual time=36.128..36.128 rows=38250 loops=1)
                     Index Cond: (name_vector @> '{12924662}'::integer[])
                     Buffers: shared hit=2 read=15
               SubPlan 1
                 ->  Aggregate  (cost=3.53..3.54 rows=1 width=0) (actual time=0.028..0.028 rows=1 loops=14)
                       ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0) (actual time=0.026..0.027 rows=1 loops=14)
                             ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=0) (actual time=0.025..0.025 rows=1 loops=14)
                                   ->  Append  (cost=0.00..3.01 rows=200 width=0) (actual time=0.003..0.017 rows=68 loops=14)
                                         ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=0) (actual time=0.002..0.003 rows=2 loops=14)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (actual time=0.002..0.003 rows=2 loops=14)
                                         ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=0) (actual time=0.001..0.010 rows=66 loops=14)
                                               ->  Result  (cost=0.00..0.51 rows=100 width=0) (actual time=0.000..0.005 rows=66 loops=14)
               SubPlan 2
                 ->  Limit  (cost=0.57..1585.37 rows=1 width=8) (actual time=16.130..16.130 rows=0 loops=14)
                       Buffers: shared hit=31 read=36
                       ->  Index Scan using idx_placex_parent_place_id on placex  (cost=0.57..1585.37 rows=1 width=8) (actual time=16.129..16.129 rows=0 loops=14)
                             Index Cond: (parent_place_id = search_name.place_id)
                             Filter: (transliteration(housenumber) ~* '\m59 l\M'::text)
                             Rows Removed by Filter: 1
                             Buffers: shared hit=31 read=36
 Planning time: 0.602 ms
 Execution time: 13320.645 ms
````

Server specs:
 - Intel Xeon E3-1246 v3
 - 8GB RAM assigned to the container
 - ZFS with 2xHDD and 2xSSDs as cache

**Comment by aaphadke** [comment] 2016-11-29 23:38
@lonvia Any suggestions on the comment I put few days back about the query plan(without caching)?

**Comment by lonvia** [comment] 2016-11-30 21:50
So the problem is that the name terms in these queries are very frequent without being marked as such. Nominatim constructs a query in this case which explicitly only uses the index on name terms and not on address terms. The result is that the index search yields 9k/27k rows which need to be loaded from disk so that they can be filtered. That's what is slow in your case: the access to rows in search_name. Is it possible that the table itself is still on a spinning disk, not an SSD? That would make the problem worse.

The easiest way to mitigate the problem is to move the search_name table to a faster disk.

Another option is to recompute the word frequencies. There is a script `sql/words.sql` which does that. However, that might have some unintended side effects because very frequent words are normally dropped from the search index on import already. If they suddenly appear again in the list of search terms in a query then these queries will always return 0 results. You should be safe, if you change the line where the frequencies are copied, so that only rows are updated where the frequency increases, i.e. something along the lines of:

    -- copy the word frequencies
    update word set search_name_count = count from word_frequencies wf where wf.id = word.word_id and count > search_name_count;

I haven't tested any of this. I recommend that you make a copy of the word table before trying it (and naturally don't do updates as long as you experiment).

**Comment by RazAlonSB** [comment] 2017-06-07 11:45
For some reason our server stopped responding to reverse geocoding requests, I'm investigating.

Compare:

http://nominatim.openstreetmap.org/reverse?lat=35.3387&lon=-91.3236&format=json

http://geocode.sparkbeyond.com/nominatim/reverse?lat=35.3387&lon=-91.3236&format=json

**Comment by lonvia** [comment] 2017-06-07 12:06
d898f9aabffdff05daa429d1f21028b302eed33d has updated the precomputed word statistics, so the problem should disappear in new installations. Existing installations can use the table but still have to follow the experimental update procedure described in the last comment. This is not recommended unless a) your database is really slow and you have no way to reimport and b) you know what you are doing.

**Closed by lonvia** 2017-06-07 12:06 UTC
