### ISSUE TITLE
Postgres DB params Issue

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1016] opened 2018-04-16 07:43 UTC
Hi,
Refer Below question. (Asked 2 years ago, But still, I met the same issue. So only raised here too).
https://help.openstreetmap.org/questions/47554/nominatim-postgres-db-argument-issue

Tried after configured in both settings.php & local.php. But still, my username not taken while connecting DB.
@define('CONST_Database_DSN', 'pgsql://nomi:nomi@/sasdb'); 

So, Every time(whenever upgrade nominatim versions) I need to edit postgresql.c and osm2pgsql/options.cpp  before compilation. 

Also, it's working if we directly give username as follows:
passthruCheckReturn('createdb -E UTF-8 **-h localhost** -p 5432 nominatim **-U mapsnomi'**)
instead of passthruCheckReturn('createdb -E UTF-8 -p '.$aDSNInfo['port'].' '.$aDSNInfo['database']);

**Comment by lonvia** [comment] 2018-04-18 22:35
Duplicate of #318. Semi-finished PR #552 waits for someone to pick it up.

**Closed by lonvia** 2018-04-18 22:35 UTC
