### ISSUE TITLE
Missing level 6 (county/district) on reverse search on XML/JSON on zoom level >09

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#789] opened 2017-09-08 08:10 UTC
seems mainly occur in Thuringia. not sure why only there.

Examples:
https://nominatim.openstreetmap.org/reverse.php?lat=50.68315&lon=12.09996&zoom=12&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=50.63074&lon=12.18145&zoom=12&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=50.92862&lon=11.99945&zoom=13&format=xml

If necessary I could provide hundreds of examples.

Possible this belongs to issue #662 

On HTML everything is fine.

Some Examples, where it works fine:
https://nominatim.openstreetmap.org/reverse.php?lat=50.49826&lon=10.90101&zoom=13&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=50.91255&lon=12.34937&zoom=13&format=xml

P.S. I've seen, I've already mentioned the bug [here](https://github.com/openstreetmap/Nominatim/issues/662#issuecomment-318923110), but no official response yet :(

**Comment by Megachip** [comment] 2017-09-08 08:14
The reason seems the existing lvl 7. If there exist a level 7, the response of xml/json getting wrong.

**Comment by Megachip** [comment] 2017-09-24 14:39
Same on Rhineland-Palatinate :(

**Comment by Megachip** [comment] 2017-10-25 17:00
Same for City_district (admin level 9) on zoom 14 and higher

Example
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=52.1022876368&lon=13.3744812012&zoom=14&format=xml

**Comment by lonvia** [comment] 2017-10-27 20:26
Duplicate of #831.

**Closed by lonvia** 2017-10-27 20:26 UTC
