### ISSUE TITLE
Search for "Tarrant County, Texas" doesn't return the county relation as the top hit

### ISSUE THREAD

**Issue by EdwardBetts** [openstreetmap/Nominatim#1031] opened 2018-05-01 21:14 UTC
https://nominatim.openstreetmap.org/search.php?q=Tarrant+County%2C+Texas&polygon_geojson=1

The top result is a location called Texas within a theme park in Tarrant County, Texas.

**Comment by lonvia** [comment] 2018-05-01 21:42
Still the same issue as you reported before. Find the object with a `addr:postcode=Texas` and fix it. 

Duplicate of #982.

**Closed by lonvia** 2018-05-01 21:42 UTC

**Comment by EdwardBetts** [comment] 2018-05-01 21:44
You mean this? https://www.openstreetmap.org/node/1214869178

Sorry if my bug report wasn't clear. The node doesn't include `addr:postcode=Texas`.

**Comment by mtmail** [comment] 2018-05-02 11:30
@EdwardBetts 
I see https://www.openstreetmap.org/way/247506590 and https://www.openstreetmap.org/way/270679006 have `addr:postcode=Texas`

I used http://overpass-turbo.eu/ to find them (zoom to Texas, use the wizard). There might be more, not sure how likely, because I only checked the Texas area.

**Comment by EdwardBetts** [comment] 2018-05-02 11:40
Thanks, I can see from Overpass it is just these two. I'll fix them and check Nominatim to see if it gives the right result.

```
(
node["addr:postcode"="Texas"]; 
rel["addr:postcode"="Texas"]; 
way["addr:postcode"="Texas"];
);
out tags;
```

**Comment by EdwardBetts** [comment] 2018-05-03 13:08
I figured out how to use Overpass to find all occurrences of this error. There are seven of them, I'm going to fix them now.
### List of errors
```
2491810533	node	California
3064249112	node	Oklahoma
3121340792	node	Georgia
42020139	way	Ohio
231010967	way	Ohio
237600110	way	Ohio
314910273	way	Ohio
```
### Overpass query
```
[out:csv(::id,::type,"addr:postcode";false)]; (
node["addr:postcode"="Alabama"];way["addr:postcode"="Alabama"];
node["addr:postcode"="Alaska"];way["addr:postcode"="Alaska"];
node["addr:postcode"="Arizona"];way["addr:postcode"="Arizona"];
node["addr:postcode"="Arkansas"];way["addr:postcode"="Arkansas"];
node["addr:postcode"="California"];way["addr:postcode"="California"];
node["addr:postcode"="Colorado"];way["addr:postcode"="Colorado"];
node["addr:postcode"="Connecticut"];way["addr:postcode"="Connecticut"];
node["addr:postcode"="Delaware"];way["addr:postcode"="Delaware"];
node["addr:postcode"="Florida"];way["addr:postcode"="Florida"];
node["addr:postcode"="Georgia"];way["addr:postcode"="Georgia"];
node["addr:postcode"="Hawaii"];way["addr:postcode"="Hawaii"];
node["addr:postcode"="Idaho"];way["addr:postcode"="Idaho"];
node["addr:postcode"="Illinois"];way["addr:postcode"="Illinois"];
node["addr:postcode"="Indiana"];way["addr:postcode"="Indiana"];
node["addr:postcode"="Iowa"];way["addr:postcode"="Iowa"];
node["addr:postcode"="Kansas"];way["addr:postcode"="Kansas"];
node["addr:postcode"="Kentucky"];way["addr:postcode"="Kentucky"];
node["addr:postcode"="Louisiana"];way["addr:postcode"="Louisiana"];
node["addr:postcode"="Maine"];way["addr:postcode"="Maine"];
node["addr:postcode"="Maryland"];way["addr:postcode"="Maryland"];
node["addr:postcode"="Massachusetts"];way["addr:postcode"="Massachusetts"];
node["addr:postcode"="Michigan"];way["addr:postcode"="Michigan"];
node["addr:postcode"="Minnesota"];way["addr:postcode"="Minnesota"];
node["addr:postcode"="Mississippi"];way["addr:postcode"="Mississippi"];
node["addr:postcode"="Missouri"];way["addr:postcode"="Missouri"];
node["addr:postcode"="Montana"];way["addr:postcode"="Montana"];
node["addr:postcode"="Nebraska"];way["addr:postcode"="Nebraska"];
node["addr:postcode"="Nevada"];way["addr:postcode"="Nevada"];
node["addr:postcode"="New Hampshire"];way["addr:postcode"="New Hampshire"];
node["addr:postcode"="New Jersey"];way["addr:postcode"="New Jersey"];
node["addr:postcode"="New Mexico"];way["addr:postcode"="New Mexico"];
node["addr:postcode"="New York"];way["addr:postcode"="New York"];
node["addr:postcode"="North Carolina"];way["addr:postcode"="North Carolina"];
node["addr:postcode"="North Dakota"];way["addr:postcode"="North Dakota"];
node["addr:postcode"="Ohio"];way["addr:postcode"="Ohio"];
node["addr:postcode"="Oklahoma"];way["addr:postcode"="Oklahoma"];
node["addr:postcode"="Oregon"];way["addr:postcode"="Oregon"];
node["addr:postcode"="Pennsylvania"];way["addr:postcode"="Pennsylvania"];
node["addr:postcode"="Rhode Island"];way["addr:postcode"="Rhode Island"];
node["addr:postcode"="South Carolina"];way["addr:postcode"="South Carolina"];
node["addr:postcode"="South Dakota"];way["addr:postcode"="South Dakota"];
node["addr:postcode"="Tennessee"];way["addr:postcode"="Tennessee"];
node["addr:postcode"="Texas"];way["addr:postcode"="Texas"];
node["addr:postcode"="Utah"];way["addr:postcode"="Utah"];
node["addr:postcode"="Vermont"];way["addr:postcode"="Vermont"];
node["addr:postcode"="Virginia"];way["addr:postcode"="Virginia"];
node["addr:postcode"="Washington"];way["addr:postcode"="Washington"];
node["addr:postcode"="West Virginia"];way["addr:postcode"="West Virginia"];
node["addr:postcode"="Wisconsin"];way["addr:postcode"="Wisconsin"];
node["addr:postcode"="Wyoming"];way["addr:postcode"="Wyoming"];
); out;
```
