### ISSUE TITLE
Nominatim database update

### ISSUE THREAD

**Issue by netstel** [openstreetmap/Nominatim#1289] opened 2019-01-25 07:38 UTC
I read here http://nominatim.org/release-docs/latest/admin/Import-and-Update/#wikipedia-rankings that files https://www.nominatim.org/data/wikipedia_article.sql.bin and https://www.nominatim.org/data/wikipedia_redirect.sql.bin should be downloaded and applied before initial import of data. I have already imported initial data before downloading these two files. Is the way to apply them to the existing database? Would "./utils/update.php --import-osmosis-all" (with wikipedia_article.sql.bin and wikipedia_redirect.sql.bin placed in data directory) do that trick?

**Comment by lonvia** [comment] 2019-01-25 09:07
No. The documentation is spot-on, it does not work after the import.

Duplicate of #255.

**Closed by lonvia** 2019-01-25 09:07 UTC
