### ISSUE TITLE
Business name is preferred to location name

### ISSUE THREAD

**Issue by blindstone** [openstreetmap/Nominatim#1625] opened 2020-01-03 14:29 UTC
When searching for "Schwedt" in Germany, the first search result returns an entry about a business rather than a town of that name.

Search term:
Schwedt

Expected result:
https://nominatim.openstreetmap.org/details.php?place_id=198143838
Actual result:
https://nominatim.openstreetmap.org/details.php?place_id=17836842

cheers!

**Comment by mtmail** [comment] 2020-01-03 18:54
I think it's the forward slash `/`. Similar city with forward slash "Fürstenwalde/Spree" https://www.openstreetmap.org/relation/1384842 Search for "Fürstenwalde" only returns the city on the second page.

**Comment by lonvia** [comment] 2020-01-13 20:01
You may add a `short_name`=`Schwedt` to these as a quick fix. Otherwise closing as duplicate of #244.

**Closed by lonvia** 2020-01-13 20:01 UTC

**Comment by lonvia** [comment] 2021-05-23 22:23
Forward slashes are tricky because they are used very inconsistently in names in OSM. I have found many different uses:

- name suffix as in "Schwedt"
- a [valid part of the name](https://www.openstreetmap.org/node/3290565079)
- a [separator for alternative names](https://www.openstreetmap.org/node/3873536273)
- a [street corner description](https://www.openstreetmap.org/node/4004946682)

In the majority of cases it is saver to consider the slash an integral part of the name and prefer that the name appears in full. That means that cases like "Schwedt" were the part before the slash could be considered a name on its own, really need an explicit `short_name`.
