### ISSUE TITLE
including suite or office number returns no results

### ISSUE THREAD

**Issue by kristiwachter** [openstreetmap/Nominatim#1399] opened 2019-06-05 04:13 UTC
If you include the suite or office number in a search, you get no results. A search for the same address without the suite or office number returns a correct result.

For example:

https://nominatim.openstreetmap.org/search.php?q=490+post+st+%23225%2C+san+francisco%2C+ca+94109&polygon_geojson=1&viewbox=

search for:
490 post st #225, san francisco, ca 94109

No results

but without the suite, it works correctly:

https://nominatim.openstreetmap.org/search.php?q=490+post+st%2C+san+francisco%2C+ca+94109&polygon_geojson=1&viewbox=

search for:
490 post st, san francisco, ca 94109

Result: Nominatim finds the correct building.

Can Nominatim strip the suite, apartment, and room number when doing lookups?

**Comment by mtmail** [comment] 2019-06-05 15:01
Nominatim can't  There's an open issue to try to integrate libpostal (https://github.com/openvenues/libpostal/) https://github.com/openstreetmap/Nominatim/issues/1119 If possible remove those numbers before querying, maybe even by using libpostal

**Comment by lonvia** [comment] 2019-06-07 21:11
Duplicate of #145.

**Closed by lonvia** 2019-06-07 21:11 UTC
