### ISSUE TITLE
Searching problems - addr:street and addr:city

### ISSUE THREAD

**Issue by NKAmapper** [openstreetmap/Nominatim#1272] opened 2019-01-02 14:30 UTC
There is an automated import of address nodes in Norway, so we have a 100% complete and correct collection of address nodes in OSM for the country. All nodes have _add:street_, _addr:housenumber_, _addr:postcode_ and _addr:city_.

However, a couple of problems causes Nominatim not to find a number of these addresses:

**1) Addresses where the _highway_ is not mapped or where the _name_ of the highway is not tagged in OSM.**

Example:

- Search: https://nominatim.openstreetmap.org/search.php?q=Krånavegen+3,+6823+Sandane
- Place: https://nominatim.openstreetmap.org/details.php?place_id=42307217

**2) Addresses where there is no direct match between _addr:city_ and a corresponding boundary or place in OSM.**

Example 1:
- Search: https://nominatim.openstreetmap.org/search.php?q=Herredsvegen+2,+2120+Sagstua
- Place: https://nominatim.openstreetmap.org/details.php?place_id=41822009

Example 2:
- Search: https://nominatim.openstreetmap.org/search.php?q=Vålgutua+202,+2436+Våler+i+Solør
- Place: https://nominatim.openstreetmap.org/details.php?place_id=42550263

The _addr:city_ names used by the postal service and for the OSM address nodes are often different from the names used in administrative boundaries and place names. And by the current rate, many highways and highway names are bound to be lacking for years to come.

Is there a way to structure the search so that Nominatim will get a hit for a correct address such as the examples above?

I am getting approx. 20% missed hits for correct addresses, which is a pity considering that they are all in OSM.

**Comment by lonvia** [comment] 2019-01-03 21:12
1) is a well known restriction of Nominatim and will not be changed. Map the street name to fix the issue. If you want to speed up the process, create a map that shows the missing streets and make it available to the Norwegian community.

2) is covered by #148. Although that particular example rather seems to be a problem that OSM has a different name (only 'Valer'). That can be easily fixed by adding the alternative name to the community.

**Closed by lonvia** 2019-01-03 21:12 UTC

**Comment by NKAmapper** [comment] 2019-01-03 21:31
Why is the strategy to not use the addr: tags?

It seems like valuable information is not used and it leads to years of extra work for a small community like ours.

**Comment by lonvia** [comment] 2019-01-03 21:44
addr: will be used eventually (for some value of eventually). This ticket is simply a duplicate of #148. No need to keep both open.
