### ISSUE TITLE
place_parent_id wrong

### ISSUE THREAD

**Issue by RemiBou** [openstreetmap/Nominatim#511] opened 2016-08-26 15:11 UTC
Hi,

I have this place :
http://nominatim.openstreetmap.org/details.php?place_id=17296552

This place is located in Maritime Alps, not in "Alpes-de-Haute-Provence". The problem is due to its parent_place_id being equal to 
http://nominatim.openstreetmap.org/details.php?place_id=142870848
instead of 
http://nominatim.openstreetmap.org/details.php?place_id=144580543

I don't know why the parent id is wrong because the geometry seems correct

**Comment by lonvia** [comment] 2016-09-27 22:11
That's because the address is taken from the road and the center of the road happens to be in Alpes-de-Haute-Provence. The bug here is that Nominatim prefers named roads when looking for the parent even when there are unnamed roads between that road and the POI in question. Quick fix would be to add a addr:place=Puget-Theniers to the camping POI, the real fix should be for Nominatim to parent the place to the unnamed road right next to it.

**Comment by lonvia** [comment] 2017-03-26 19:22
Duplicate of #79.

**Closed by lonvia** 2017-03-26 19:22 UTC
Labels: bug, duplicate, Indexing
