### ISSUE TITLE
similarity search with one digit/character difference

### ISSUE THREAD

**Issue by joy-yyd** [openstreetmap/Nominatim#1703] opened 2020-03-02 12:05 UTC
Hello, I have read that Nominatim supports the strict search and suggested to use Photon or other engine for the search-as-you-type. However, we are interested and willing to contribute to get results with one digit difference as the following example:
**Found:**  https://nominatim.openstreetmap.org/search.php?q=Eichenweg+42%2C+06849+Dessau&polygon_geojson=1&viewbox=

**Not Found: ** https://nominatim.openstreetmap.org/search.php?q=Eichenweg+42%2C+06845+Dessau&polygon_geojson=1&viewbox=

Could you give us some hints about the current status and some suggestion of modification regarding one digit/character typo tolerance. Thanks a lot for your advice in advance!

**Comment by lonvia** [comment] 2020-03-04 08:10
This is not as easy as you think it is. You can't just search for similar words going by editing distance, you need to find meaningful similarities. And you need to do that in an environment where you don't know much about the language of the query or the language of the searched for item. If you get it wrong, you'll find that many search results that were right before are now suddenly wrong.

Closing as duplicate of #145.

**Closed by lonvia** 2020-03-04 08:10 UTC
