### ISSUE TITLE
i can't get latitude longitude from address

### ISSUE THREAD

**Issue by strivedge** [openstreetmap/Nominatim#1349] opened 2019-04-05 10:22 UTC
i get blank array when i am trying to get latitude longitude using this api 'https://nominatim.openstreetmap.org/format=json&addressdetails=1&q=1130+E+Desert+Inn+Rd,+Las+Vegas,+NV+89109,+USA&format=json&limit=1' Plese help me to solve this problem

**Comment by jarek** [comment] 2019-04-09 21:17
In this case it appears that Nominatim is really confused by the fact that this address is not with city limits of Las Vegas. https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=1130+E+Desert+Inn+Rd,+NV+89109,+USA&format=json&limit=1 (with "Las Vegas" removed) works.

Per https://nominatim.openstreetmap.org/details.php?place_id=220909341 the address is computed as being in Midtown UNLV, Winchester, Paradise, Clark County, but not Las Vegas.

**Comment by lonvia** [comment] 2019-04-10 20:26
Yet another problem with US postal towns not matching admin boundaries.

Duplicate of #1120.

**Closed by lonvia** 2019-04-10 20:26 UTC
